open System
open System.IO
open System.Net
open System.Text.RegularExpressions

module Lucide =
    let input =
        File.ReadAllText "../Docs/node_modules/lucide-react/dist/lucide-react.d.ts"

    let iconsNames =
        Regex.Match(input, "export {([^}]+)").Groups[1].Value.Split(',')
        |> Array.map (fun s -> Regex.Match(s, "as ([^\s]+)").Groups[1].Value)

    let w = File.CreateText(__SOURCE_DIRECTORY__ + "/Lucide.fs")

    w.WriteLine(
        """// This file is auto-generated by the Lucide.fsx script

namespace Feliz.Shadcn

open Fable.Core
open Fable.Core.JsInterop
open Feliz

module svg =
    let size (value: int) = svg.custom("size", value)
    let color (value: string) = svg.custom("color", value)
    let absoluteStrokeWidth (value: bool) = svg.custom("absoluteStrokeWidth", value)

[<Erase>]
type Lucide ="""
    )

    for iconName in iconsNames do
        w.WriteLine(
            $"""    static member inline %s{iconName} (props: list<ISvgAttribute>) = Interop.reactApi.createElement(import "%s{iconName}" "lucide-react", createObj !!props)"""
        )

    w.Close()
