// This file is auto-generated by the Generate.fsx script

namespace Feliz.Shadcn

[<AutoOpen>]
module Props =
    open Fable.Core
    open Fable.Core.JsInterop
    open Feliz
    open Feliz.Shadcn.Helpers

    [<Erase>]
    type accordion =
        static member item (props: IReactProperty seq) = createElement(import "AccordionItem" "@/components/ui/accordion") props
        static member item (children: #seq<ReactElement>) = createElement(import "AccordionItem" "@/components/ui/accordion") [ prop.children (children :> ReactElement seq) ]
        static member item (text: string) = createElement(import "AccordionItem" "@/components/ui/accordion") [ prop.text text ]
        static member trigger (props: IReactProperty seq) = createElement(import "AccordionTrigger" "@/components/ui/accordion") props
        static member trigger (children: #seq<ReactElement>) = createElement(import "AccordionTrigger" "@/components/ui/accordion") [ prop.children (children :> ReactElement seq) ]
        static member trigger (text: string) = createElement(import "AccordionTrigger" "@/components/ui/accordion") [ prop.text text ]
        static member content (props: IReactProperty seq) = createElement(import "AccordionContent" "@/components/ui/accordion") props
        static member content (children: #seq<ReactElement>) = createElement(import "AccordionContent" "@/components/ui/accordion") [ prop.children (children :> ReactElement seq) ]
        static member content (text: string) = createElement(import "AccordionContent" "@/components/ui/accordion") [ prop.text text ]

    [<Erase>]
    type alertDialog =
        static member portal (props: IReactProperty seq) = createElement(import "AlertDialogPortal" "@/components/ui/alert-dialog") props
        static member portal (children: #seq<ReactElement>) = createElement(import "AlertDialogPortal" "@/components/ui/alert-dialog") [ prop.children (children :> ReactElement seq) ]
        static member portal (text: string) = createElement(import "AlertDialogPortal" "@/components/ui/alert-dialog") [ prop.text text ]
        static member overlay (props: IReactProperty seq) = createElement(import "AlertDialogOverlay" "@/components/ui/alert-dialog") props
        static member overlay (children: #seq<ReactElement>) = createElement(import "AlertDialogOverlay" "@/components/ui/alert-dialog") [ prop.children (children :> ReactElement seq) ]
        static member overlay (text: string) = createElement(import "AlertDialogOverlay" "@/components/ui/alert-dialog") [ prop.text text ]
        static member trigger (props: IReactProperty seq) = createElement(import "AlertDialogTrigger" "@/components/ui/alert-dialog") props
        static member trigger (children: #seq<ReactElement>) = createElement(import "AlertDialogTrigger" "@/components/ui/alert-dialog") [ prop.children (children :> ReactElement seq) ]
        static member trigger (text: string) = createElement(import "AlertDialogTrigger" "@/components/ui/alert-dialog") [ prop.text text ]
        static member content (props: IReactProperty seq) = createElement(import "AlertDialogContent" "@/components/ui/alert-dialog") props
        static member content (children: #seq<ReactElement>) = createElement(import "AlertDialogContent" "@/components/ui/alert-dialog") [ prop.children (children :> ReactElement seq) ]
        static member content (text: string) = createElement(import "AlertDialogContent" "@/components/ui/alert-dialog") [ prop.text text ]
        static member header (props: IReactProperty seq) = createElement(import "AlertDialogHeader" "@/components/ui/alert-dialog") props
        static member header (children: #seq<ReactElement>) = createElement(import "AlertDialogHeader" "@/components/ui/alert-dialog") [ prop.children (children :> ReactElement seq) ]
        static member header (text: string) = createElement(import "AlertDialogHeader" "@/components/ui/alert-dialog") [ prop.text text ]
        static member footer (props: IReactProperty seq) = createElement(import "AlertDialogFooter" "@/components/ui/alert-dialog") props
        static member footer (children: #seq<ReactElement>) = createElement(import "AlertDialogFooter" "@/components/ui/alert-dialog") [ prop.children (children :> ReactElement seq) ]
        static member footer (text: string) = createElement(import "AlertDialogFooter" "@/components/ui/alert-dialog") [ prop.text text ]
        static member title (props: IReactProperty seq) = createElement(import "AlertDialogTitle" "@/components/ui/alert-dialog") props
        static member title (children: #seq<ReactElement>) = createElement(import "AlertDialogTitle" "@/components/ui/alert-dialog") [ prop.children (children :> ReactElement seq) ]
        static member title (text: string) = createElement(import "AlertDialogTitle" "@/components/ui/alert-dialog") [ prop.text text ]
        static member description (props: IReactProperty seq) = createElement(import "AlertDialogDescription" "@/components/ui/alert-dialog") props
        static member description (children: #seq<ReactElement>) = createElement(import "AlertDialogDescription" "@/components/ui/alert-dialog") [ prop.children (children :> ReactElement seq) ]
        static member description (text: string) = createElement(import "AlertDialogDescription" "@/components/ui/alert-dialog") [ prop.text text ]
        static member action (props: IReactProperty seq) = createElement(import "AlertDialogAction" "@/components/ui/alert-dialog") props
        static member action (children: #seq<ReactElement>) = createElement(import "AlertDialogAction" "@/components/ui/alert-dialog") [ prop.children (children :> ReactElement seq) ]
        static member action (text: string) = createElement(import "AlertDialogAction" "@/components/ui/alert-dialog") [ prop.text text ]
        static member cancel (props: IReactProperty seq) = createElement(import "AlertDialogCancel" "@/components/ui/alert-dialog") props
        static member cancel (children: #seq<ReactElement>) = createElement(import "AlertDialogCancel" "@/components/ui/alert-dialog") [ prop.children (children :> ReactElement seq) ]
        static member cancel (text: string) = createElement(import "AlertDialogCancel" "@/components/ui/alert-dialog") [ prop.text text ]

    [<Erase>]
    type alert =
        static member title (props: IReactProperty seq) = createElement(import "AlertTitle" "@/components/ui/alert") props
        static member title (children: #seq<ReactElement>) = createElement(import "AlertTitle" "@/components/ui/alert") [ prop.children (children :> ReactElement seq) ]
        static member title (text: string) = createElement(import "AlertTitle" "@/components/ui/alert") [ prop.text text ]
        static member description (props: IReactProperty seq) = createElement(import "AlertDescription" "@/components/ui/alert") props
        static member description (children: #seq<ReactElement>) = createElement(import "AlertDescription" "@/components/ui/alert") [ prop.children (children :> ReactElement seq) ]
        static member description (text: string) = createElement(import "AlertDescription" "@/components/ui/alert") [ prop.text text ]

    [<Erase>]
    type avatar =
        static member image (props: IReactProperty seq) = createElement(import "AvatarImage" "@/components/ui/avatar") props
        static member image (children: #seq<ReactElement>) = createElement(import "AvatarImage" "@/components/ui/avatar") [ prop.children (children :> ReactElement seq) ]
        static member image (text: string) = createElement(import "AvatarImage" "@/components/ui/avatar") [ prop.text text ]
        static member fallback (props: IReactProperty seq) = createElement(import "AvatarFallback" "@/components/ui/avatar") props
        static member fallback (children: #seq<ReactElement>) = createElement(import "AvatarFallback" "@/components/ui/avatar") [ prop.children (children :> ReactElement seq) ]
        static member fallback (text: string) = createElement(import "AvatarFallback" "@/components/ui/avatar") [ prop.text text ]

    [<Erase>]
    type breadcrumb =
        static member list (props: IReactProperty seq) = createElement(import "BreadcrumbList" "@/components/ui/breadcrumb") props
        static member list (children: #seq<ReactElement>) = createElement(import "BreadcrumbList" "@/components/ui/breadcrumb") [ prop.children (children :> ReactElement seq) ]
        static member list (text: string) = createElement(import "BreadcrumbList" "@/components/ui/breadcrumb") [ prop.text text ]
        static member item (props: IReactProperty seq) = createElement(import "BreadcrumbItem" "@/components/ui/breadcrumb") props
        static member item (children: #seq<ReactElement>) = createElement(import "BreadcrumbItem" "@/components/ui/breadcrumb") [ prop.children (children :> ReactElement seq) ]
        static member item (text: string) = createElement(import "BreadcrumbItem" "@/components/ui/breadcrumb") [ prop.text text ]
        static member link (props: IReactProperty seq) = createElement(import "BreadcrumbLink" "@/components/ui/breadcrumb") props
        static member link (children: #seq<ReactElement>) = createElement(import "BreadcrumbLink" "@/components/ui/breadcrumb") [ prop.children (children :> ReactElement seq) ]
        static member link (text: string) = createElement(import "BreadcrumbLink" "@/components/ui/breadcrumb") [ prop.text text ]
        static member page (props: IReactProperty seq) = createElement(import "BreadcrumbPage" "@/components/ui/breadcrumb") props
        static member page (children: #seq<ReactElement>) = createElement(import "BreadcrumbPage" "@/components/ui/breadcrumb") [ prop.children (children :> ReactElement seq) ]
        static member page (text: string) = createElement(import "BreadcrumbPage" "@/components/ui/breadcrumb") [ prop.text text ]
        static member separator (props: IReactProperty seq) = createElement(import "BreadcrumbSeparator" "@/components/ui/breadcrumb") props
        static member separator (children: #seq<ReactElement>) = createElement(import "BreadcrumbSeparator" "@/components/ui/breadcrumb") [ prop.children (children :> ReactElement seq) ]
        static member separator (text: string) = createElement(import "BreadcrumbSeparator" "@/components/ui/breadcrumb") [ prop.text text ]
        static member ellipsis (props: IReactProperty seq) = createElement(import "BreadcrumbEllipsis" "@/components/ui/breadcrumb") props
        static member ellipsis (children: #seq<ReactElement>) = createElement(import "BreadcrumbEllipsis" "@/components/ui/breadcrumb") [ prop.children (children :> ReactElement seq) ]
        static member ellipsis (text: string) = createElement(import "BreadcrumbEllipsis" "@/components/ui/breadcrumb") [ prop.text text ]

    [<Erase>]
    type card =
        static member header (props: IReactProperty seq) = createElement(import "CardHeader" "@/components/ui/card") props
        static member header (children: #seq<ReactElement>) = createElement(import "CardHeader" "@/components/ui/card") [ prop.children (children :> ReactElement seq) ]
        static member header (text: string) = createElement(import "CardHeader" "@/components/ui/card") [ prop.text text ]
        static member footer (props: IReactProperty seq) = createElement(import "CardFooter" "@/components/ui/card") props
        static member footer (children: #seq<ReactElement>) = createElement(import "CardFooter" "@/components/ui/card") [ prop.children (children :> ReactElement seq) ]
        static member footer (text: string) = createElement(import "CardFooter" "@/components/ui/card") [ prop.text text ]
        static member title (props: IReactProperty seq) = createElement(import "CardTitle" "@/components/ui/card") props
        static member title (children: #seq<ReactElement>) = createElement(import "CardTitle" "@/components/ui/card") [ prop.children (children :> ReactElement seq) ]
        static member title (text: string) = createElement(import "CardTitle" "@/components/ui/card") [ prop.text text ]
        static member description (props: IReactProperty seq) = createElement(import "CardDescription" "@/components/ui/card") props
        static member description (children: #seq<ReactElement>) = createElement(import "CardDescription" "@/components/ui/card") [ prop.children (children :> ReactElement seq) ]
        static member description (text: string) = createElement(import "CardDescription" "@/components/ui/card") [ prop.text text ]
        static member content (props: IReactProperty seq) = createElement(import "CardContent" "@/components/ui/card") props
        static member content (children: #seq<ReactElement>) = createElement(import "CardContent" "@/components/ui/card") [ prop.children (children :> ReactElement seq) ]
        static member content (text: string) = createElement(import "CardContent" "@/components/ui/card") [ prop.text text ]

    [<Erase>]
    type collapsible =
        static member trigger (props: IReactProperty seq) = createElement(import "CollapsibleTrigger" "@/components/ui/collapsible") props
        static member trigger (children: #seq<ReactElement>) = createElement(import "CollapsibleTrigger" "@/components/ui/collapsible") [ prop.children (children :> ReactElement seq) ]
        static member trigger (text: string) = createElement(import "CollapsibleTrigger" "@/components/ui/collapsible") [ prop.text text ]
        static member content (props: IReactProperty seq) = createElement(import "CollapsibleContent" "@/components/ui/collapsible") props
        static member content (children: #seq<ReactElement>) = createElement(import "CollapsibleContent" "@/components/ui/collapsible") [ prop.children (children :> ReactElement seq) ]
        static member content (text: string) = createElement(import "CollapsibleContent" "@/components/ui/collapsible") [ prop.text text ]

    [<Erase>]
    type command =
        static member dialog (props: IReactProperty seq) = createElement(import "CommandDialog" "@/components/ui/command") props
        static member dialog (children: #seq<ReactElement>) = createElement(import "CommandDialog" "@/components/ui/command") [ prop.children (children :> ReactElement seq) ]
        static member dialog (text: string) = createElement(import "CommandDialog" "@/components/ui/command") [ prop.text text ]
        static member input (props: IReactProperty seq) = createElement(import "CommandInput" "@/components/ui/command") props
        static member input (children: #seq<ReactElement>) = createElement(import "CommandInput" "@/components/ui/command") [ prop.children (children :> ReactElement seq) ]
        static member input (text: string) = createElement(import "CommandInput" "@/components/ui/command") [ prop.text text ]
        static member list (props: IReactProperty seq) = createElement(import "CommandList" "@/components/ui/command") props
        static member list (children: #seq<ReactElement>) = createElement(import "CommandList" "@/components/ui/command") [ prop.children (children :> ReactElement seq) ]
        static member list (text: string) = createElement(import "CommandList" "@/components/ui/command") [ prop.text text ]
        static member empty (props: IReactProperty seq) = createElement(import "CommandEmpty" "@/components/ui/command") props
        static member empty (children: #seq<ReactElement>) = createElement(import "CommandEmpty" "@/components/ui/command") [ prop.children (children :> ReactElement seq) ]
        static member empty (text: string) = createElement(import "CommandEmpty" "@/components/ui/command") [ prop.text text ]
        static member group (props: IReactProperty seq) = createElement(import "CommandGroup" "@/components/ui/command") props
        static member group (children: #seq<ReactElement>) = createElement(import "CommandGroup" "@/components/ui/command") [ prop.children (children :> ReactElement seq) ]
        static member group (text: string) = createElement(import "CommandGroup" "@/components/ui/command") [ prop.text text ]
        static member item (props: IReactProperty seq) = createElement(import "CommandItem" "@/components/ui/command") props
        static member item (children: #seq<ReactElement>) = createElement(import "CommandItem" "@/components/ui/command") [ prop.children (children :> ReactElement seq) ]
        static member item (text: string) = createElement(import "CommandItem" "@/components/ui/command") [ prop.text text ]
        static member shortcut (props: IReactProperty seq) = createElement(import "CommandShortcut" "@/components/ui/command") props
        static member shortcut (children: #seq<ReactElement>) = createElement(import "CommandShortcut" "@/components/ui/command") [ prop.children (children :> ReactElement seq) ]
        static member shortcut (text: string) = createElement(import "CommandShortcut" "@/components/ui/command") [ prop.text text ]
        static member separator (props: IReactProperty seq) = createElement(import "CommandSeparator" "@/components/ui/command") props
        static member separator (children: #seq<ReactElement>) = createElement(import "CommandSeparator" "@/components/ui/command") [ prop.children (children :> ReactElement seq) ]
        static member separator (text: string) = createElement(import "CommandSeparator" "@/components/ui/command") [ prop.text text ]

    [<Erase>]
    type contextMenu =
        static member trigger (props: IReactProperty seq) = createElement(import "ContextMenuTrigger" "@/components/ui/context-menu") props
        static member trigger (children: #seq<ReactElement>) = createElement(import "ContextMenuTrigger" "@/components/ui/context-menu") [ prop.children (children :> ReactElement seq) ]
        static member trigger (text: string) = createElement(import "ContextMenuTrigger" "@/components/ui/context-menu") [ prop.text text ]
        static member content (props: IReactProperty seq) = createElement(import "ContextMenuContent" "@/components/ui/context-menu") props
        static member content (children: #seq<ReactElement>) = createElement(import "ContextMenuContent" "@/components/ui/context-menu") [ prop.children (children :> ReactElement seq) ]
        static member content (text: string) = createElement(import "ContextMenuContent" "@/components/ui/context-menu") [ prop.text text ]
        static member item (props: IReactProperty seq) = createElement(import "ContextMenuItem" "@/components/ui/context-menu") props
        static member item (children: #seq<ReactElement>) = createElement(import "ContextMenuItem" "@/components/ui/context-menu") [ prop.children (children :> ReactElement seq) ]
        static member item (text: string) = createElement(import "ContextMenuItem" "@/components/ui/context-menu") [ prop.text text ]
        static member checkboxItem (props: IReactProperty seq) = createElement(import "ContextMenuCheckboxItem" "@/components/ui/context-menu") props
        static member checkboxItem (children: #seq<ReactElement>) = createElement(import "ContextMenuCheckboxItem" "@/components/ui/context-menu") [ prop.children (children :> ReactElement seq) ]
        static member checkboxItem (text: string) = createElement(import "ContextMenuCheckboxItem" "@/components/ui/context-menu") [ prop.text text ]
        static member radioItem (props: IReactProperty seq) = createElement(import "ContextMenuRadioItem" "@/components/ui/context-menu") props
        static member radioItem (children: #seq<ReactElement>) = createElement(import "ContextMenuRadioItem" "@/components/ui/context-menu") [ prop.children (children :> ReactElement seq) ]
        static member radioItem (text: string) = createElement(import "ContextMenuRadioItem" "@/components/ui/context-menu") [ prop.text text ]
        static member label (props: IReactProperty seq) = createElement(import "ContextMenuLabel" "@/components/ui/context-menu") props
        static member label (children: #seq<ReactElement>) = createElement(import "ContextMenuLabel" "@/components/ui/context-menu") [ prop.children (children :> ReactElement seq) ]
        static member label (text: string) = createElement(import "ContextMenuLabel" "@/components/ui/context-menu") [ prop.text text ]
        static member separator (props: IReactProperty seq) = createElement(import "ContextMenuSeparator" "@/components/ui/context-menu") props
        static member separator (children: #seq<ReactElement>) = createElement(import "ContextMenuSeparator" "@/components/ui/context-menu") [ prop.children (children :> ReactElement seq) ]
        static member separator (text: string) = createElement(import "ContextMenuSeparator" "@/components/ui/context-menu") [ prop.text text ]
        static member shortcut (props: IReactProperty seq) = createElement(import "ContextMenuShortcut" "@/components/ui/context-menu") props
        static member shortcut (children: #seq<ReactElement>) = createElement(import "ContextMenuShortcut" "@/components/ui/context-menu") [ prop.children (children :> ReactElement seq) ]
        static member shortcut (text: string) = createElement(import "ContextMenuShortcut" "@/components/ui/context-menu") [ prop.text text ]
        static member group (props: IReactProperty seq) = createElement(import "ContextMenuGroup" "@/components/ui/context-menu") props
        static member group (children: #seq<ReactElement>) = createElement(import "ContextMenuGroup" "@/components/ui/context-menu") [ prop.children (children :> ReactElement seq) ]
        static member group (text: string) = createElement(import "ContextMenuGroup" "@/components/ui/context-menu") [ prop.text text ]
        static member portal (props: IReactProperty seq) = createElement(import "ContextMenuPortal" "@/components/ui/context-menu") props
        static member portal (children: #seq<ReactElement>) = createElement(import "ContextMenuPortal" "@/components/ui/context-menu") [ prop.children (children :> ReactElement seq) ]
        static member portal (text: string) = createElement(import "ContextMenuPortal" "@/components/ui/context-menu") [ prop.text text ]
        static member sub (props: IReactProperty seq) = createElement(import "ContextMenuSub" "@/components/ui/context-menu") props
        static member sub (children: #seq<ReactElement>) = createElement(import "ContextMenuSub" "@/components/ui/context-menu") [ prop.children (children :> ReactElement seq) ]
        static member sub (text: string) = createElement(import "ContextMenuSub" "@/components/ui/context-menu") [ prop.text text ]
        static member subContent (props: IReactProperty seq) = createElement(import "ContextMenuSubContent" "@/components/ui/context-menu") props
        static member subContent (children: #seq<ReactElement>) = createElement(import "ContextMenuSubContent" "@/components/ui/context-menu") [ prop.children (children :> ReactElement seq) ]
        static member subContent (text: string) = createElement(import "ContextMenuSubContent" "@/components/ui/context-menu") [ prop.text text ]
        static member subTrigger (props: IReactProperty seq) = createElement(import "ContextMenuSubTrigger" "@/components/ui/context-menu") props
        static member subTrigger (children: #seq<ReactElement>) = createElement(import "ContextMenuSubTrigger" "@/components/ui/context-menu") [ prop.children (children :> ReactElement seq) ]
        static member subTrigger (text: string) = createElement(import "ContextMenuSubTrigger" "@/components/ui/context-menu") [ prop.text text ]
        static member radioGroup (props: IReactProperty seq) = createElement(import "ContextMenuRadioGroup" "@/components/ui/context-menu") props
        static member radioGroup (children: #seq<ReactElement>) = createElement(import "ContextMenuRadioGroup" "@/components/ui/context-menu") [ prop.children (children :> ReactElement seq) ]
        static member radioGroup (text: string) = createElement(import "ContextMenuRadioGroup" "@/components/ui/context-menu") [ prop.text text ]

    [<Erase>]
    type dialog =
        static member close (props: IReactProperty seq) = createElement(import "DialogClose" "@/components/ui/dialog") props
        static member close (children: #seq<ReactElement>) = createElement(import "DialogClose" "@/components/ui/dialog") [ prop.children (children :> ReactElement seq) ]
        static member close (text: string) = createElement(import "DialogClose" "@/components/ui/dialog") [ prop.text text ]
        static member content (props: IReactProperty seq) = createElement(import "DialogContent" "@/components/ui/dialog") props
        static member content (children: #seq<ReactElement>) = createElement(import "DialogContent" "@/components/ui/dialog") [ prop.children (children :> ReactElement seq) ]
        static member content (text: string) = createElement(import "DialogContent" "@/components/ui/dialog") [ prop.text text ]
        static member description (props: IReactProperty seq) = createElement(import "DialogDescription" "@/components/ui/dialog") props
        static member description (children: #seq<ReactElement>) = createElement(import "DialogDescription" "@/components/ui/dialog") [ prop.children (children :> ReactElement seq) ]
        static member description (text: string) = createElement(import "DialogDescription" "@/components/ui/dialog") [ prop.text text ]
        static member footer (props: IReactProperty seq) = createElement(import "DialogFooter" "@/components/ui/dialog") props
        static member footer (children: #seq<ReactElement>) = createElement(import "DialogFooter" "@/components/ui/dialog") [ prop.children (children :> ReactElement seq) ]
        static member footer (text: string) = createElement(import "DialogFooter" "@/components/ui/dialog") [ prop.text text ]
        static member header (props: IReactProperty seq) = createElement(import "DialogHeader" "@/components/ui/dialog") props
        static member header (children: #seq<ReactElement>) = createElement(import "DialogHeader" "@/components/ui/dialog") [ prop.children (children :> ReactElement seq) ]
        static member header (text: string) = createElement(import "DialogHeader" "@/components/ui/dialog") [ prop.text text ]
        static member overlay (props: IReactProperty seq) = createElement(import "DialogOverlay" "@/components/ui/dialog") props
        static member overlay (children: #seq<ReactElement>) = createElement(import "DialogOverlay" "@/components/ui/dialog") [ prop.children (children :> ReactElement seq) ]
        static member overlay (text: string) = createElement(import "DialogOverlay" "@/components/ui/dialog") [ prop.text text ]
        static member portal (props: IReactProperty seq) = createElement(import "DialogPortal" "@/components/ui/dialog") props
        static member portal (children: #seq<ReactElement>) = createElement(import "DialogPortal" "@/components/ui/dialog") [ prop.children (children :> ReactElement seq) ]
        static member portal (text: string) = createElement(import "DialogPortal" "@/components/ui/dialog") [ prop.text text ]
        static member title (props: IReactProperty seq) = createElement(import "DialogTitle" "@/components/ui/dialog") props
        static member title (children: #seq<ReactElement>) = createElement(import "DialogTitle" "@/components/ui/dialog") [ prop.children (children :> ReactElement seq) ]
        static member title (text: string) = createElement(import "DialogTitle" "@/components/ui/dialog") [ prop.text text ]
        static member trigger (props: IReactProperty seq) = createElement(import "DialogTrigger" "@/components/ui/dialog") props
        static member trigger (children: #seq<ReactElement>) = createElement(import "DialogTrigger" "@/components/ui/dialog") [ prop.children (children :> ReactElement seq) ]
        static member trigger (text: string) = createElement(import "DialogTrigger" "@/components/ui/dialog") [ prop.text text ]

    [<Erase>]
    type drawer =
        static member portal (props: IReactProperty seq) = createElement(import "DrawerPortal" "@/components/ui/drawer") props
        static member portal (children: #seq<ReactElement>) = createElement(import "DrawerPortal" "@/components/ui/drawer") [ prop.children (children :> ReactElement seq) ]
        static member portal (text: string) = createElement(import "DrawerPortal" "@/components/ui/drawer") [ prop.text text ]
        static member overlay (props: IReactProperty seq) = createElement(import "DrawerOverlay" "@/components/ui/drawer") props
        static member overlay (children: #seq<ReactElement>) = createElement(import "DrawerOverlay" "@/components/ui/drawer") [ prop.children (children :> ReactElement seq) ]
        static member overlay (text: string) = createElement(import "DrawerOverlay" "@/components/ui/drawer") [ prop.text text ]
        static member trigger (props: IReactProperty seq) = createElement(import "DrawerTrigger" "@/components/ui/drawer") props
        static member trigger (children: #seq<ReactElement>) = createElement(import "DrawerTrigger" "@/components/ui/drawer") [ prop.children (children :> ReactElement seq) ]
        static member trigger (text: string) = createElement(import "DrawerTrigger" "@/components/ui/drawer") [ prop.text text ]
        static member close (props: IReactProperty seq) = createElement(import "DrawerClose" "@/components/ui/drawer") props
        static member close (children: #seq<ReactElement>) = createElement(import "DrawerClose" "@/components/ui/drawer") [ prop.children (children :> ReactElement seq) ]
        static member close (text: string) = createElement(import "DrawerClose" "@/components/ui/drawer") [ prop.text text ]
        static member content (props: IReactProperty seq) = createElement(import "DrawerContent" "@/components/ui/drawer") props
        static member content (children: #seq<ReactElement>) = createElement(import "DrawerContent" "@/components/ui/drawer") [ prop.children (children :> ReactElement seq) ]
        static member content (text: string) = createElement(import "DrawerContent" "@/components/ui/drawer") [ prop.text text ]
        static member header (props: IReactProperty seq) = createElement(import "DrawerHeader" "@/components/ui/drawer") props
        static member header (children: #seq<ReactElement>) = createElement(import "DrawerHeader" "@/components/ui/drawer") [ prop.children (children :> ReactElement seq) ]
        static member header (text: string) = createElement(import "DrawerHeader" "@/components/ui/drawer") [ prop.text text ]
        static member footer (props: IReactProperty seq) = createElement(import "DrawerFooter" "@/components/ui/drawer") props
        static member footer (children: #seq<ReactElement>) = createElement(import "DrawerFooter" "@/components/ui/drawer") [ prop.children (children :> ReactElement seq) ]
        static member footer (text: string) = createElement(import "DrawerFooter" "@/components/ui/drawer") [ prop.text text ]
        static member title (props: IReactProperty seq) = createElement(import "DrawerTitle" "@/components/ui/drawer") props
        static member title (children: #seq<ReactElement>) = createElement(import "DrawerTitle" "@/components/ui/drawer") [ prop.children (children :> ReactElement seq) ]
        static member title (text: string) = createElement(import "DrawerTitle" "@/components/ui/drawer") [ prop.text text ]
        static member description (props: IReactProperty seq) = createElement(import "DrawerDescription" "@/components/ui/drawer") props
        static member description (children: #seq<ReactElement>) = createElement(import "DrawerDescription" "@/components/ui/drawer") [ prop.children (children :> ReactElement seq) ]
        static member description (text: string) = createElement(import "DrawerDescription" "@/components/ui/drawer") [ prop.text text ]

    [<Erase>]
    type dropdownMenu =
        static member portal (props: IReactProperty seq) = createElement(import "DropdownMenuPortal" "@/components/ui/dropdown-menu") props
        static member portal (children: #seq<ReactElement>) = createElement(import "DropdownMenuPortal" "@/components/ui/dropdown-menu") [ prop.children (children :> ReactElement seq) ]
        static member portal (text: string) = createElement(import "DropdownMenuPortal" "@/components/ui/dropdown-menu") [ prop.text text ]
        static member trigger (props: IReactProperty seq) = createElement(import "DropdownMenuTrigger" "@/components/ui/dropdown-menu") props
        static member trigger (children: #seq<ReactElement>) = createElement(import "DropdownMenuTrigger" "@/components/ui/dropdown-menu") [ prop.children (children :> ReactElement seq) ]
        static member trigger (text: string) = createElement(import "DropdownMenuTrigger" "@/components/ui/dropdown-menu") [ prop.text text ]
        static member content (props: IReactProperty seq) = createElement(import "DropdownMenuContent" "@/components/ui/dropdown-menu") props
        static member content (children: #seq<ReactElement>) = createElement(import "DropdownMenuContent" "@/components/ui/dropdown-menu") [ prop.children (children :> ReactElement seq) ]
        static member content (text: string) = createElement(import "DropdownMenuContent" "@/components/ui/dropdown-menu") [ prop.text text ]
        static member group (props: IReactProperty seq) = createElement(import "DropdownMenuGroup" "@/components/ui/dropdown-menu") props
        static member group (children: #seq<ReactElement>) = createElement(import "DropdownMenuGroup" "@/components/ui/dropdown-menu") [ prop.children (children :> ReactElement seq) ]
        static member group (text: string) = createElement(import "DropdownMenuGroup" "@/components/ui/dropdown-menu") [ prop.text text ]
        static member label (props: IReactProperty seq) = createElement(import "DropdownMenuLabel" "@/components/ui/dropdown-menu") props
        static member label (children: #seq<ReactElement>) = createElement(import "DropdownMenuLabel" "@/components/ui/dropdown-menu") [ prop.children (children :> ReactElement seq) ]
        static member label (text: string) = createElement(import "DropdownMenuLabel" "@/components/ui/dropdown-menu") [ prop.text text ]
        static member item (props: IReactProperty seq) = createElement(import "DropdownMenuItem" "@/components/ui/dropdown-menu") props
        static member item (children: #seq<ReactElement>) = createElement(import "DropdownMenuItem" "@/components/ui/dropdown-menu") [ prop.children (children :> ReactElement seq) ]
        static member item (text: string) = createElement(import "DropdownMenuItem" "@/components/ui/dropdown-menu") [ prop.text text ]
        static member checkboxItem (props: IReactProperty seq) = createElement(import "DropdownMenuCheckboxItem" "@/components/ui/dropdown-menu") props
        static member checkboxItem (children: #seq<ReactElement>) = createElement(import "DropdownMenuCheckboxItem" "@/components/ui/dropdown-menu") [ prop.children (children :> ReactElement seq) ]
        static member checkboxItem (text: string) = createElement(import "DropdownMenuCheckboxItem" "@/components/ui/dropdown-menu") [ prop.text text ]
        static member radioGroup (props: IReactProperty seq) = createElement(import "DropdownMenuRadioGroup" "@/components/ui/dropdown-menu") props
        static member radioGroup (children: #seq<ReactElement>) = createElement(import "DropdownMenuRadioGroup" "@/components/ui/dropdown-menu") [ prop.children (children :> ReactElement seq) ]
        static member radioGroup (text: string) = createElement(import "DropdownMenuRadioGroup" "@/components/ui/dropdown-menu") [ prop.text text ]
        static member radioItem (props: IReactProperty seq) = createElement(import "DropdownMenuRadioItem" "@/components/ui/dropdown-menu") props
        static member radioItem (children: #seq<ReactElement>) = createElement(import "DropdownMenuRadioItem" "@/components/ui/dropdown-menu") [ prop.children (children :> ReactElement seq) ]
        static member radioItem (text: string) = createElement(import "DropdownMenuRadioItem" "@/components/ui/dropdown-menu") [ prop.text text ]
        static member separator (props: IReactProperty seq) = createElement(import "DropdownMenuSeparator" "@/components/ui/dropdown-menu") props
        static member separator (children: #seq<ReactElement>) = createElement(import "DropdownMenuSeparator" "@/components/ui/dropdown-menu") [ prop.children (children :> ReactElement seq) ]
        static member separator (text: string) = createElement(import "DropdownMenuSeparator" "@/components/ui/dropdown-menu") [ prop.text text ]
        static member shortcut (props: IReactProperty seq) = createElement(import "DropdownMenuShortcut" "@/components/ui/dropdown-menu") props
        static member shortcut (children: #seq<ReactElement>) = createElement(import "DropdownMenuShortcut" "@/components/ui/dropdown-menu") [ prop.children (children :> ReactElement seq) ]
        static member shortcut (text: string) = createElement(import "DropdownMenuShortcut" "@/components/ui/dropdown-menu") [ prop.text text ]
        static member sub (props: IReactProperty seq) = createElement(import "DropdownMenuSub" "@/components/ui/dropdown-menu") props
        static member sub (children: #seq<ReactElement>) = createElement(import "DropdownMenuSub" "@/components/ui/dropdown-menu") [ prop.children (children :> ReactElement seq) ]
        static member sub (text: string) = createElement(import "DropdownMenuSub" "@/components/ui/dropdown-menu") [ prop.text text ]
        static member subTrigger (props: IReactProperty seq) = createElement(import "DropdownMenuSubTrigger" "@/components/ui/dropdown-menu") props
        static member subTrigger (children: #seq<ReactElement>) = createElement(import "DropdownMenuSubTrigger" "@/components/ui/dropdown-menu") [ prop.children (children :> ReactElement seq) ]
        static member subTrigger (text: string) = createElement(import "DropdownMenuSubTrigger" "@/components/ui/dropdown-menu") [ prop.text text ]
        static member subContent (props: IReactProperty seq) = createElement(import "DropdownMenuSubContent" "@/components/ui/dropdown-menu") props
        static member subContent (children: #seq<ReactElement>) = createElement(import "DropdownMenuSubContent" "@/components/ui/dropdown-menu") [ prop.children (children :> ReactElement seq) ]
        static member subContent (text: string) = createElement(import "DropdownMenuSubContent" "@/components/ui/dropdown-menu") [ prop.text text ]

    [<Erase>]
    type hoverCard =
        static member trigger (props: IReactProperty seq) = createElement(import "HoverCardTrigger" "@/components/ui/hover-card") props
        static member trigger (children: #seq<ReactElement>) = createElement(import "HoverCardTrigger" "@/components/ui/hover-card") [ prop.children (children :> ReactElement seq) ]
        static member trigger (text: string) = createElement(import "HoverCardTrigger" "@/components/ui/hover-card") [ prop.text text ]
        static member content (props: IReactProperty seq) = createElement(import "HoverCardContent" "@/components/ui/hover-card") props
        static member content (children: #seq<ReactElement>) = createElement(import "HoverCardContent" "@/components/ui/hover-card") [ prop.children (children :> ReactElement seq) ]
        static member content (text: string) = createElement(import "HoverCardContent" "@/components/ui/hover-card") [ prop.text text ]

    [<Erase>]
    type inputOTP =
        static member group (props: IReactProperty seq) = createElement(import "InputOTPGroup" "@/components/ui/input-otp") props
        static member group (children: #seq<ReactElement>) = createElement(import "InputOTPGroup" "@/components/ui/input-otp") [ prop.children (children :> ReactElement seq) ]
        static member group (text: string) = createElement(import "InputOTPGroup" "@/components/ui/input-otp") [ prop.text text ]
        static member slot (props: IReactProperty seq) = createElement(import "InputOTPSlot" "@/components/ui/input-otp") props
        static member slot (children: #seq<ReactElement>) = createElement(import "InputOTPSlot" "@/components/ui/input-otp") [ prop.children (children :> ReactElement seq) ]
        static member slot (text: string) = createElement(import "InputOTPSlot" "@/components/ui/input-otp") [ prop.text text ]
        static member separator (props: IReactProperty seq) = createElement(import "InputOTPSeparator" "@/components/ui/input-otp") props
        static member separator (children: #seq<ReactElement>) = createElement(import "InputOTPSeparator" "@/components/ui/input-otp") [ prop.children (children :> ReactElement seq) ]
        static member separator (text: string) = createElement(import "InputOTPSeparator" "@/components/ui/input-otp") [ prop.text text ]

    [<Erase>]
    type menubar =
        static member portal (props: IReactProperty seq) = createElement(import "MenubarPortal" "@/components/ui/menubar") props
        static member portal (children: #seq<ReactElement>) = createElement(import "MenubarPortal" "@/components/ui/menubar") [ prop.children (children :> ReactElement seq) ]
        static member portal (text: string) = createElement(import "MenubarPortal" "@/components/ui/menubar") [ prop.text text ]
        static member menu (props: IReactProperty seq) = createElement(import "MenubarMenu" "@/components/ui/menubar") props
        static member menu (children: #seq<ReactElement>) = createElement(import "MenubarMenu" "@/components/ui/menubar") [ prop.children (children :> ReactElement seq) ]
        static member menu (text: string) = createElement(import "MenubarMenu" "@/components/ui/menubar") [ prop.text text ]
        static member trigger (props: IReactProperty seq) = createElement(import "MenubarTrigger" "@/components/ui/menubar") props
        static member trigger (children: #seq<ReactElement>) = createElement(import "MenubarTrigger" "@/components/ui/menubar") [ prop.children (children :> ReactElement seq) ]
        static member trigger (text: string) = createElement(import "MenubarTrigger" "@/components/ui/menubar") [ prop.text text ]
        static member content (props: IReactProperty seq) = createElement(import "MenubarContent" "@/components/ui/menubar") props
        static member content (children: #seq<ReactElement>) = createElement(import "MenubarContent" "@/components/ui/menubar") [ prop.children (children :> ReactElement seq) ]
        static member content (text: string) = createElement(import "MenubarContent" "@/components/ui/menubar") [ prop.text text ]
        static member group (props: IReactProperty seq) = createElement(import "MenubarGroup" "@/components/ui/menubar") props
        static member group (children: #seq<ReactElement>) = createElement(import "MenubarGroup" "@/components/ui/menubar") [ prop.children (children :> ReactElement seq) ]
        static member group (text: string) = createElement(import "MenubarGroup" "@/components/ui/menubar") [ prop.text text ]
        static member separator (props: IReactProperty seq) = createElement(import "MenubarSeparator" "@/components/ui/menubar") props
        static member separator (children: #seq<ReactElement>) = createElement(import "MenubarSeparator" "@/components/ui/menubar") [ prop.children (children :> ReactElement seq) ]
        static member separator (text: string) = createElement(import "MenubarSeparator" "@/components/ui/menubar") [ prop.text text ]
        static member label (props: IReactProperty seq) = createElement(import "MenubarLabel" "@/components/ui/menubar") props
        static member label (children: #seq<ReactElement>) = createElement(import "MenubarLabel" "@/components/ui/menubar") [ prop.children (children :> ReactElement seq) ]
        static member label (text: string) = createElement(import "MenubarLabel" "@/components/ui/menubar") [ prop.text text ]
        static member item (props: IReactProperty seq) = createElement(import "MenubarItem" "@/components/ui/menubar") props
        static member item (children: #seq<ReactElement>) = createElement(import "MenubarItem" "@/components/ui/menubar") [ prop.children (children :> ReactElement seq) ]
        static member item (text: string) = createElement(import "MenubarItem" "@/components/ui/menubar") [ prop.text text ]
        static member shortcut (props: IReactProperty seq) = createElement(import "MenubarShortcut" "@/components/ui/menubar") props
        static member shortcut (children: #seq<ReactElement>) = createElement(import "MenubarShortcut" "@/components/ui/menubar") [ prop.children (children :> ReactElement seq) ]
        static member shortcut (text: string) = createElement(import "MenubarShortcut" "@/components/ui/menubar") [ prop.text text ]
        static member checkboxItem (props: IReactProperty seq) = createElement(import "MenubarCheckboxItem" "@/components/ui/menubar") props
        static member checkboxItem (children: #seq<ReactElement>) = createElement(import "MenubarCheckboxItem" "@/components/ui/menubar") [ prop.children (children :> ReactElement seq) ]
        static member checkboxItem (text: string) = createElement(import "MenubarCheckboxItem" "@/components/ui/menubar") [ prop.text text ]
        static member radioGroup (props: IReactProperty seq) = createElement(import "MenubarRadioGroup" "@/components/ui/menubar") props
        static member radioGroup (children: #seq<ReactElement>) = createElement(import "MenubarRadioGroup" "@/components/ui/menubar") [ prop.children (children :> ReactElement seq) ]
        static member radioGroup (text: string) = createElement(import "MenubarRadioGroup" "@/components/ui/menubar") [ prop.text text ]
        static member radioItem (props: IReactProperty seq) = createElement(import "MenubarRadioItem" "@/components/ui/menubar") props
        static member radioItem (children: #seq<ReactElement>) = createElement(import "MenubarRadioItem" "@/components/ui/menubar") [ prop.children (children :> ReactElement seq) ]
        static member radioItem (text: string) = createElement(import "MenubarRadioItem" "@/components/ui/menubar") [ prop.text text ]
        static member sub (props: IReactProperty seq) = createElement(import "MenubarSub" "@/components/ui/menubar") props
        static member sub (children: #seq<ReactElement>) = createElement(import "MenubarSub" "@/components/ui/menubar") [ prop.children (children :> ReactElement seq) ]
        static member sub (text: string) = createElement(import "MenubarSub" "@/components/ui/menubar") [ prop.text text ]
        static member subTrigger (props: IReactProperty seq) = createElement(import "MenubarSubTrigger" "@/components/ui/menubar") props
        static member subTrigger (children: #seq<ReactElement>) = createElement(import "MenubarSubTrigger" "@/components/ui/menubar") [ prop.children (children :> ReactElement seq) ]
        static member subTrigger (text: string) = createElement(import "MenubarSubTrigger" "@/components/ui/menubar") [ prop.text text ]
        static member subContent (props: IReactProperty seq) = createElement(import "MenubarSubContent" "@/components/ui/menubar") props
        static member subContent (children: #seq<ReactElement>) = createElement(import "MenubarSubContent" "@/components/ui/menubar") [ prop.children (children :> ReactElement seq) ]
        static member subContent (text: string) = createElement(import "MenubarSubContent" "@/components/ui/menubar") [ prop.text text ]

    [<Erase>]
    type navigationMenu =
        static member list (props: IReactProperty seq) = createElement(import "NavigationMenuList" "@/components/ui/navigation-menu") props
        static member list (children: #seq<ReactElement>) = createElement(import "NavigationMenuList" "@/components/ui/navigation-menu") [ prop.children (children :> ReactElement seq) ]
        static member list (text: string) = createElement(import "NavigationMenuList" "@/components/ui/navigation-menu") [ prop.text text ]
        static member item (props: IReactProperty seq) = createElement(import "NavigationMenuItem" "@/components/ui/navigation-menu") props
        static member item (children: #seq<ReactElement>) = createElement(import "NavigationMenuItem" "@/components/ui/navigation-menu") [ prop.children (children :> ReactElement seq) ]
        static member item (text: string) = createElement(import "NavigationMenuItem" "@/components/ui/navigation-menu") [ prop.text text ]
        static member content (props: IReactProperty seq) = createElement(import "NavigationMenuContent" "@/components/ui/navigation-menu") props
        static member content (children: #seq<ReactElement>) = createElement(import "NavigationMenuContent" "@/components/ui/navigation-menu") [ prop.children (children :> ReactElement seq) ]
        static member content (text: string) = createElement(import "NavigationMenuContent" "@/components/ui/navigation-menu") [ prop.text text ]
        static member trigger (props: IReactProperty seq) = createElement(import "NavigationMenuTrigger" "@/components/ui/navigation-menu") props
        static member trigger (children: #seq<ReactElement>) = createElement(import "NavigationMenuTrigger" "@/components/ui/navigation-menu") [ prop.children (children :> ReactElement seq) ]
        static member trigger (text: string) = createElement(import "NavigationMenuTrigger" "@/components/ui/navigation-menu") [ prop.text text ]
        static member link (props: IReactProperty seq) = createElement(import "NavigationMenuLink" "@/components/ui/navigation-menu") props
        static member link (children: #seq<ReactElement>) = createElement(import "NavigationMenuLink" "@/components/ui/navigation-menu") [ prop.children (children :> ReactElement seq) ]
        static member link (text: string) = createElement(import "NavigationMenuLink" "@/components/ui/navigation-menu") [ prop.text text ]
        static member indicator (props: IReactProperty seq) = createElement(import "NavigationMenuIndicator" "@/components/ui/navigation-menu") props
        static member indicator (children: #seq<ReactElement>) = createElement(import "NavigationMenuIndicator" "@/components/ui/navigation-menu") [ prop.children (children :> ReactElement seq) ]
        static member indicator (text: string) = createElement(import "NavigationMenuIndicator" "@/components/ui/navigation-menu") [ prop.text text ]
        static member viewport (props: IReactProperty seq) = createElement(import "NavigationMenuViewport" "@/components/ui/navigation-menu") props
        static member viewport (children: #seq<ReactElement>) = createElement(import "NavigationMenuViewport" "@/components/ui/navigation-menu") [ prop.children (children :> ReactElement seq) ]
        static member viewport (text: string) = createElement(import "NavigationMenuViewport" "@/components/ui/navigation-menu") [ prop.text text ]

    [<Erase>]
    type pagination =
        static member content (props: IReactProperty seq) = createElement(import "PaginationContent" "@/components/ui/pagination") props
        static member content (children: #seq<ReactElement>) = createElement(import "PaginationContent" "@/components/ui/pagination") [ prop.children (children :> ReactElement seq) ]
        static member content (text: string) = createElement(import "PaginationContent" "@/components/ui/pagination") [ prop.text text ]
        static member link (props: IReactProperty seq) = createElement(import "PaginationLink" "@/components/ui/pagination") props
        static member link (children: #seq<ReactElement>) = createElement(import "PaginationLink" "@/components/ui/pagination") [ prop.children (children :> ReactElement seq) ]
        static member link (text: string) = createElement(import "PaginationLink" "@/components/ui/pagination") [ prop.text text ]
        static member item (props: IReactProperty seq) = createElement(import "PaginationItem" "@/components/ui/pagination") props
        static member item (children: #seq<ReactElement>) = createElement(import "PaginationItem" "@/components/ui/pagination") [ prop.children (children :> ReactElement seq) ]
        static member item (text: string) = createElement(import "PaginationItem" "@/components/ui/pagination") [ prop.text text ]
        static member previous (props: IReactProperty seq) = createElement(import "PaginationPrevious" "@/components/ui/pagination") props
        static member previous (children: #seq<ReactElement>) = createElement(import "PaginationPrevious" "@/components/ui/pagination") [ prop.children (children :> ReactElement seq) ]
        static member previous (text: string) = createElement(import "PaginationPrevious" "@/components/ui/pagination") [ prop.text text ]
        static member next (props: IReactProperty seq) = createElement(import "PaginationNext" "@/components/ui/pagination") props
        static member next (children: #seq<ReactElement>) = createElement(import "PaginationNext" "@/components/ui/pagination") [ prop.children (children :> ReactElement seq) ]
        static member next (text: string) = createElement(import "PaginationNext" "@/components/ui/pagination") [ prop.text text ]
        static member ellipsis (props: IReactProperty seq) = createElement(import "PaginationEllipsis" "@/components/ui/pagination") props
        static member ellipsis (children: #seq<ReactElement>) = createElement(import "PaginationEllipsis" "@/components/ui/pagination") [ prop.children (children :> ReactElement seq) ]
        static member ellipsis (text: string) = createElement(import "PaginationEllipsis" "@/components/ui/pagination") [ prop.text text ]

    [<Erase>]
    type popover =
        static member trigger (props: IReactProperty seq) = createElement(import "PopoverTrigger" "@/components/ui/popover") props
        static member trigger (children: #seq<ReactElement>) = createElement(import "PopoverTrigger" "@/components/ui/popover") [ prop.children (children :> ReactElement seq) ]
        static member trigger (text: string) = createElement(import "PopoverTrigger" "@/components/ui/popover") [ prop.text text ]
        static member content (props: IReactProperty seq) = createElement(import "PopoverContent" "@/components/ui/popover") props
        static member content (children: #seq<ReactElement>) = createElement(import "PopoverContent" "@/components/ui/popover") [ prop.children (children :> ReactElement seq) ]
        static member content (text: string) = createElement(import "PopoverContent" "@/components/ui/popover") [ prop.text text ]
        static member anchor (props: IReactProperty seq) = createElement(import "PopoverAnchor" "@/components/ui/popover") props
        static member anchor (children: #seq<ReactElement>) = createElement(import "PopoverAnchor" "@/components/ui/popover") [ prop.children (children :> ReactElement seq) ]
        static member anchor (text: string) = createElement(import "PopoverAnchor" "@/components/ui/popover") [ prop.text text ]

    [<Erase>]
    type radioGroup =
        static member item (props: IReactProperty seq) = createElement(import "RadioGroupItem" "@/components/ui/radio-group") props
        static member item (children: #seq<ReactElement>) = createElement(import "RadioGroupItem" "@/components/ui/radio-group") [ prop.children (children :> ReactElement seq) ]
        static member item (text: string) = createElement(import "RadioGroupItem" "@/components/ui/radio-group") [ prop.text text ]

    [<Erase>]
    type select =
        static member content (props: IReactProperty seq) = createElement(import "SelectContent" "@/components/ui/select") props
        static member content (children: #seq<ReactElement>) = createElement(import "SelectContent" "@/components/ui/select") [ prop.children (children :> ReactElement seq) ]
        static member content (text: string) = createElement(import "SelectContent" "@/components/ui/select") [ prop.text text ]
        static member group (props: IReactProperty seq) = createElement(import "SelectGroup" "@/components/ui/select") props
        static member group (children: #seq<ReactElement>) = createElement(import "SelectGroup" "@/components/ui/select") [ prop.children (children :> ReactElement seq) ]
        static member group (text: string) = createElement(import "SelectGroup" "@/components/ui/select") [ prop.text text ]
        static member item (props: IReactProperty seq) = createElement(import "SelectItem" "@/components/ui/select") props
        static member item (children: #seq<ReactElement>) = createElement(import "SelectItem" "@/components/ui/select") [ prop.children (children :> ReactElement seq) ]
        static member item (text: string) = createElement(import "SelectItem" "@/components/ui/select") [ prop.text text ]
        static member label (props: IReactProperty seq) = createElement(import "SelectLabel" "@/components/ui/select") props
        static member label (children: #seq<ReactElement>) = createElement(import "SelectLabel" "@/components/ui/select") [ prop.children (children :> ReactElement seq) ]
        static member label (text: string) = createElement(import "SelectLabel" "@/components/ui/select") [ prop.text text ]
        static member scrollDownButton (props: IReactProperty seq) = createElement(import "SelectScrollDownButton" "@/components/ui/select") props
        static member scrollDownButton (children: #seq<ReactElement>) = createElement(import "SelectScrollDownButton" "@/components/ui/select") [ prop.children (children :> ReactElement seq) ]
        static member scrollDownButton (text: string) = createElement(import "SelectScrollDownButton" "@/components/ui/select") [ prop.text text ]
        static member scrollUpButton (props: IReactProperty seq) = createElement(import "SelectScrollUpButton" "@/components/ui/select") props
        static member scrollUpButton (children: #seq<ReactElement>) = createElement(import "SelectScrollUpButton" "@/components/ui/select") [ prop.children (children :> ReactElement seq) ]
        static member scrollUpButton (text: string) = createElement(import "SelectScrollUpButton" "@/components/ui/select") [ prop.text text ]
        static member separator (props: IReactProperty seq) = createElement(import "SelectSeparator" "@/components/ui/select") props
        static member separator (children: #seq<ReactElement>) = createElement(import "SelectSeparator" "@/components/ui/select") [ prop.children (children :> ReactElement seq) ]
        static member separator (text: string) = createElement(import "SelectSeparator" "@/components/ui/select") [ prop.text text ]
        static member trigger (props: IReactProperty seq) = createElement(import "SelectTrigger" "@/components/ui/select") props
        static member trigger (children: #seq<ReactElement>) = createElement(import "SelectTrigger" "@/components/ui/select") [ prop.children (children :> ReactElement seq) ]
        static member trigger (text: string) = createElement(import "SelectTrigger" "@/components/ui/select") [ prop.text text ]
        static member value (props: IReactProperty seq) = createElement(import "SelectValue" "@/components/ui/select") props
        static member value (children: #seq<ReactElement>) = createElement(import "SelectValue" "@/components/ui/select") [ prop.children (children :> ReactElement seq) ]
        static member value (text: string) = createElement(import "SelectValue" "@/components/ui/select") [ prop.text text ]

    [<Erase>]
    type sheet =
        static member trigger (props: IReactProperty seq) = createElement(import "SheetTrigger" "@/components/ui/sheet") props
        static member trigger (children: #seq<ReactElement>) = createElement(import "SheetTrigger" "@/components/ui/sheet") [ prop.children (children :> ReactElement seq) ]
        static member trigger (text: string) = createElement(import "SheetTrigger" "@/components/ui/sheet") [ prop.text text ]
        static member close (props: IReactProperty seq) = createElement(import "SheetClose" "@/components/ui/sheet") props
        static member close (children: #seq<ReactElement>) = createElement(import "SheetClose" "@/components/ui/sheet") [ prop.children (children :> ReactElement seq) ]
        static member close (text: string) = createElement(import "SheetClose" "@/components/ui/sheet") [ prop.text text ]
        static member content (props: IReactProperty seq) = createElement(import "SheetContent" "@/components/ui/sheet") props
        static member content (children: #seq<ReactElement>) = createElement(import "SheetContent" "@/components/ui/sheet") [ prop.children (children :> ReactElement seq) ]
        static member content (text: string) = createElement(import "SheetContent" "@/components/ui/sheet") [ prop.text text ]
        static member header (props: IReactProperty seq) = createElement(import "SheetHeader" "@/components/ui/sheet") props
        static member header (children: #seq<ReactElement>) = createElement(import "SheetHeader" "@/components/ui/sheet") [ prop.children (children :> ReactElement seq) ]
        static member header (text: string) = createElement(import "SheetHeader" "@/components/ui/sheet") [ prop.text text ]
        static member footer (props: IReactProperty seq) = createElement(import "SheetFooter" "@/components/ui/sheet") props
        static member footer (children: #seq<ReactElement>) = createElement(import "SheetFooter" "@/components/ui/sheet") [ prop.children (children :> ReactElement seq) ]
        static member footer (text: string) = createElement(import "SheetFooter" "@/components/ui/sheet") [ prop.text text ]
        static member title (props: IReactProperty seq) = createElement(import "SheetTitle" "@/components/ui/sheet") props
        static member title (children: #seq<ReactElement>) = createElement(import "SheetTitle" "@/components/ui/sheet") [ prop.children (children :> ReactElement seq) ]
        static member title (text: string) = createElement(import "SheetTitle" "@/components/ui/sheet") [ prop.text text ]
        static member description (props: IReactProperty seq) = createElement(import "SheetDescription" "@/components/ui/sheet") props
        static member description (children: #seq<ReactElement>) = createElement(import "SheetDescription" "@/components/ui/sheet") [ prop.children (children :> ReactElement seq) ]
        static member description (text: string) = createElement(import "SheetDescription" "@/components/ui/sheet") [ prop.text text ]

    [<Erase>]
    type sidebar =
        static member content (props: IReactProperty seq) = createElement(import "SidebarContent" "@/components/ui/sidebar") props
        static member content (children: #seq<ReactElement>) = createElement(import "SidebarContent" "@/components/ui/sidebar") [ prop.children (children :> ReactElement seq) ]
        static member content (text: string) = createElement(import "SidebarContent" "@/components/ui/sidebar") [ prop.text text ]
        static member footer (props: IReactProperty seq) = createElement(import "SidebarFooter" "@/components/ui/sidebar") props
        static member footer (children: #seq<ReactElement>) = createElement(import "SidebarFooter" "@/components/ui/sidebar") [ prop.children (children :> ReactElement seq) ]
        static member footer (text: string) = createElement(import "SidebarFooter" "@/components/ui/sidebar") [ prop.text text ]
        static member group (props: IReactProperty seq) = createElement(import "SidebarGroup" "@/components/ui/sidebar") props
        static member group (children: #seq<ReactElement>) = createElement(import "SidebarGroup" "@/components/ui/sidebar") [ prop.children (children :> ReactElement seq) ]
        static member group (text: string) = createElement(import "SidebarGroup" "@/components/ui/sidebar") [ prop.text text ]
        static member groupAction (props: IReactProperty seq) = createElement(import "SidebarGroupAction" "@/components/ui/sidebar") props
        static member groupAction (children: #seq<ReactElement>) = createElement(import "SidebarGroupAction" "@/components/ui/sidebar") [ prop.children (children :> ReactElement seq) ]
        static member groupAction (text: string) = createElement(import "SidebarGroupAction" "@/components/ui/sidebar") [ prop.text text ]
        static member groupContent (props: IReactProperty seq) = createElement(import "SidebarGroupContent" "@/components/ui/sidebar") props
        static member groupContent (children: #seq<ReactElement>) = createElement(import "SidebarGroupContent" "@/components/ui/sidebar") [ prop.children (children :> ReactElement seq) ]
        static member groupContent (text: string) = createElement(import "SidebarGroupContent" "@/components/ui/sidebar") [ prop.text text ]
        static member groupLabel (props: IReactProperty seq) = createElement(import "SidebarGroupLabel" "@/components/ui/sidebar") props
        static member groupLabel (children: #seq<ReactElement>) = createElement(import "SidebarGroupLabel" "@/components/ui/sidebar") [ prop.children (children :> ReactElement seq) ]
        static member groupLabel (text: string) = createElement(import "SidebarGroupLabel" "@/components/ui/sidebar") [ prop.text text ]
        static member header (props: IReactProperty seq) = createElement(import "SidebarHeader" "@/components/ui/sidebar") props
        static member header (children: #seq<ReactElement>) = createElement(import "SidebarHeader" "@/components/ui/sidebar") [ prop.children (children :> ReactElement seq) ]
        static member header (text: string) = createElement(import "SidebarHeader" "@/components/ui/sidebar") [ prop.text text ]
        static member input (props: IReactProperty seq) = createElement(import "SidebarInput" "@/components/ui/sidebar") props
        static member input (children: #seq<ReactElement>) = createElement(import "SidebarInput" "@/components/ui/sidebar") [ prop.children (children :> ReactElement seq) ]
        static member input (text: string) = createElement(import "SidebarInput" "@/components/ui/sidebar") [ prop.text text ]
        static member inset (props: IReactProperty seq) = createElement(import "SidebarInset" "@/components/ui/sidebar") props
        static member inset (children: #seq<ReactElement>) = createElement(import "SidebarInset" "@/components/ui/sidebar") [ prop.children (children :> ReactElement seq) ]
        static member inset (text: string) = createElement(import "SidebarInset" "@/components/ui/sidebar") [ prop.text text ]
        static member menu (props: IReactProperty seq) = createElement(import "SidebarMenu" "@/components/ui/sidebar") props
        static member menu (children: #seq<ReactElement>) = createElement(import "SidebarMenu" "@/components/ui/sidebar") [ prop.children (children :> ReactElement seq) ]
        static member menu (text: string) = createElement(import "SidebarMenu" "@/components/ui/sidebar") [ prop.text text ]
        static member menuAction (props: IReactProperty seq) = createElement(import "SidebarMenuAction" "@/components/ui/sidebar") props
        static member menuAction (children: #seq<ReactElement>) = createElement(import "SidebarMenuAction" "@/components/ui/sidebar") [ prop.children (children :> ReactElement seq) ]
        static member menuAction (text: string) = createElement(import "SidebarMenuAction" "@/components/ui/sidebar") [ prop.text text ]
        static member menuBadge (props: IReactProperty seq) = createElement(import "SidebarMenuBadge" "@/components/ui/sidebar") props
        static member menuBadge (children: #seq<ReactElement>) = createElement(import "SidebarMenuBadge" "@/components/ui/sidebar") [ prop.children (children :> ReactElement seq) ]
        static member menuBadge (text: string) = createElement(import "SidebarMenuBadge" "@/components/ui/sidebar") [ prop.text text ]
        static member menuButton (props: IReactProperty seq) = createElement(import "SidebarMenuButton" "@/components/ui/sidebar") props
        static member menuButton (children: #seq<ReactElement>) = createElement(import "SidebarMenuButton" "@/components/ui/sidebar") [ prop.children (children :> ReactElement seq) ]
        static member menuButton (text: string) = createElement(import "SidebarMenuButton" "@/components/ui/sidebar") [ prop.text text ]
        static member menuItem (props: IReactProperty seq) = createElement(import "SidebarMenuItem" "@/components/ui/sidebar") props
        static member menuItem (children: #seq<ReactElement>) = createElement(import "SidebarMenuItem" "@/components/ui/sidebar") [ prop.children (children :> ReactElement seq) ]
        static member menuItem (text: string) = createElement(import "SidebarMenuItem" "@/components/ui/sidebar") [ prop.text text ]
        static member menuSkeleton (props: IReactProperty seq) = createElement(import "SidebarMenuSkeleton" "@/components/ui/sidebar") props
        static member menuSkeleton (children: #seq<ReactElement>) = createElement(import "SidebarMenuSkeleton" "@/components/ui/sidebar") [ prop.children (children :> ReactElement seq) ]
        static member menuSkeleton (text: string) = createElement(import "SidebarMenuSkeleton" "@/components/ui/sidebar") [ prop.text text ]
        static member menuSub (props: IReactProperty seq) = createElement(import "SidebarMenuSub" "@/components/ui/sidebar") props
        static member menuSub (children: #seq<ReactElement>) = createElement(import "SidebarMenuSub" "@/components/ui/sidebar") [ prop.children (children :> ReactElement seq) ]
        static member menuSub (text: string) = createElement(import "SidebarMenuSub" "@/components/ui/sidebar") [ prop.text text ]
        static member menuSubButton (props: IReactProperty seq) = createElement(import "SidebarMenuSubButton" "@/components/ui/sidebar") props
        static member menuSubButton (children: #seq<ReactElement>) = createElement(import "SidebarMenuSubButton" "@/components/ui/sidebar") [ prop.children (children :> ReactElement seq) ]
        static member menuSubButton (text: string) = createElement(import "SidebarMenuSubButton" "@/components/ui/sidebar") [ prop.text text ]
        static member menuSubItem (props: IReactProperty seq) = createElement(import "SidebarMenuSubItem" "@/components/ui/sidebar") props
        static member menuSubItem (children: #seq<ReactElement>) = createElement(import "SidebarMenuSubItem" "@/components/ui/sidebar") [ prop.children (children :> ReactElement seq) ]
        static member menuSubItem (text: string) = createElement(import "SidebarMenuSubItem" "@/components/ui/sidebar") [ prop.text text ]
        static member provider (props: IReactProperty seq) = createElement(import "SidebarProvider" "@/components/ui/sidebar") props
        static member provider (children: #seq<ReactElement>) = createElement(import "SidebarProvider" "@/components/ui/sidebar") [ prop.children (children :> ReactElement seq) ]
        static member provider (text: string) = createElement(import "SidebarProvider" "@/components/ui/sidebar") [ prop.text text ]
        static member rail (props: IReactProperty seq) = createElement(import "SidebarRail" "@/components/ui/sidebar") props
        static member rail (children: #seq<ReactElement>) = createElement(import "SidebarRail" "@/components/ui/sidebar") [ prop.children (children :> ReactElement seq) ]
        static member rail (text: string) = createElement(import "SidebarRail" "@/components/ui/sidebar") [ prop.text text ]
        static member separator (props: IReactProperty seq) = createElement(import "SidebarSeparator" "@/components/ui/sidebar") props
        static member separator (children: #seq<ReactElement>) = createElement(import "SidebarSeparator" "@/components/ui/sidebar") [ prop.children (children :> ReactElement seq) ]
        static member separator (text: string) = createElement(import "SidebarSeparator" "@/components/ui/sidebar") [ prop.text text ]
        static member trigger (props: IReactProperty seq) = createElement(import "SidebarTrigger" "@/components/ui/sidebar") props
        static member trigger (children: #seq<ReactElement>) = createElement(import "SidebarTrigger" "@/components/ui/sidebar") [ prop.children (children :> ReactElement seq) ]
        static member trigger (text: string) = createElement(import "SidebarTrigger" "@/components/ui/sidebar") [ prop.text text ]

    [<Erase>]
    type table =
        static member header (props: IReactProperty seq) = createElement(import "TableHeader" "@/components/ui/table") props
        static member header (children: #seq<ReactElement>) = createElement(import "TableHeader" "@/components/ui/table") [ prop.children (children :> ReactElement seq) ]
        static member header (text: string) = createElement(import "TableHeader" "@/components/ui/table") [ prop.text text ]
        static member body (props: IReactProperty seq) = createElement(import "TableBody" "@/components/ui/table") props
        static member body (children: #seq<ReactElement>) = createElement(import "TableBody" "@/components/ui/table") [ prop.children (children :> ReactElement seq) ]
        static member body (text: string) = createElement(import "TableBody" "@/components/ui/table") [ prop.text text ]
        static member footer (props: IReactProperty seq) = createElement(import "TableFooter" "@/components/ui/table") props
        static member footer (children: #seq<ReactElement>) = createElement(import "TableFooter" "@/components/ui/table") [ prop.children (children :> ReactElement seq) ]
        static member footer (text: string) = createElement(import "TableFooter" "@/components/ui/table") [ prop.text text ]
        static member head (props: IReactProperty seq) = createElement(import "TableHead" "@/components/ui/table") props
        static member head (children: #seq<ReactElement>) = createElement(import "TableHead" "@/components/ui/table") [ prop.children (children :> ReactElement seq) ]
        static member head (text: string) = createElement(import "TableHead" "@/components/ui/table") [ prop.text text ]
        static member row (props: IReactProperty seq) = createElement(import "TableRow" "@/components/ui/table") props
        static member row (children: #seq<ReactElement>) = createElement(import "TableRow" "@/components/ui/table") [ prop.children (children :> ReactElement seq) ]
        static member row (text: string) = createElement(import "TableRow" "@/components/ui/table") [ prop.text text ]
        static member cell (props: IReactProperty seq) = createElement(import "TableCell" "@/components/ui/table") props
        static member cell (children: #seq<ReactElement>) = createElement(import "TableCell" "@/components/ui/table") [ prop.children (children :> ReactElement seq) ]
        static member cell (text: string) = createElement(import "TableCell" "@/components/ui/table") [ prop.text text ]
        static member caption (props: IReactProperty seq) = createElement(import "TableCaption" "@/components/ui/table") props
        static member caption (children: #seq<ReactElement>) = createElement(import "TableCaption" "@/components/ui/table") [ prop.children (children :> ReactElement seq) ]
        static member caption (text: string) = createElement(import "TableCaption" "@/components/ui/table") [ prop.text text ]

    [<Erase>]
    type tabs =
        static member list (props: IReactProperty seq) = createElement(import "TabsList" "@/components/ui/tabs") props
        static member list (children: #seq<ReactElement>) = createElement(import "TabsList" "@/components/ui/tabs") [ prop.children (children :> ReactElement seq) ]
        static member list (text: string) = createElement(import "TabsList" "@/components/ui/tabs") [ prop.text text ]
        static member trigger (props: IReactProperty seq) = createElement(import "TabsTrigger" "@/components/ui/tabs") props
        static member trigger (children: #seq<ReactElement>) = createElement(import "TabsTrigger" "@/components/ui/tabs") [ prop.children (children :> ReactElement seq) ]
        static member trigger (text: string) = createElement(import "TabsTrigger" "@/components/ui/tabs") [ prop.text text ]
        static member content (props: IReactProperty seq) = createElement(import "TabsContent" "@/components/ui/tabs") props
        static member content (children: #seq<ReactElement>) = createElement(import "TabsContent" "@/components/ui/tabs") [ prop.children (children :> ReactElement seq) ]
        static member content (text: string) = createElement(import "TabsContent" "@/components/ui/tabs") [ prop.text text ]

    [<Erase>]
    type toggleGroup =
        static member item (props: IReactProperty seq) = createElement(import "ToggleGroupItem" "@/components/ui/toggle-group") props
        static member item (children: #seq<ReactElement>) = createElement(import "ToggleGroupItem" "@/components/ui/toggle-group") [ prop.children (children :> ReactElement seq) ]
        static member item (text: string) = createElement(import "ToggleGroupItem" "@/components/ui/toggle-group") [ prop.text text ]

    [<Erase>]
    type tooltip =
        static member trigger (props: IReactProperty seq) = createElement(import "TooltipTrigger" "@/components/ui/tooltip") props
        static member trigger (children: #seq<ReactElement>) = createElement(import "TooltipTrigger" "@/components/ui/tooltip") [ prop.children (children :> ReactElement seq) ]
        static member trigger (text: string) = createElement(import "TooltipTrigger" "@/components/ui/tooltip") [ prop.text text ]
        static member content (props: IReactProperty seq) = createElement(import "TooltipContent" "@/components/ui/tooltip") props
        static member content (children: #seq<ReactElement>) = createElement(import "TooltipContent" "@/components/ui/tooltip") [ prop.children (children :> ReactElement seq) ]
        static member content (text: string) = createElement(import "TooltipContent" "@/components/ui/tooltip") [ prop.text text ]
        static member provider (props: IReactProperty seq) = createElement(import "TooltipProvider" "@/components/ui/tooltip") props
        static member provider (children: #seq<ReactElement>) = createElement(import "TooltipProvider" "@/components/ui/tooltip") [ prop.children (children :> ReactElement seq) ]
        static member provider (text: string) = createElement(import "TooltipProvider" "@/components/ui/tooltip") [ prop.text text ]

