// This file is auto-generated by the Generate.fsx script

namespace Feliz.Shadcn

[<AutoOpen>]
module RadixUI =
    open System.ComponentModel
    open Browser.Types
    open Fable.Core
    open Fable.Core.JsInterop
    open Feliz

    [<EditorBrowsable(EditorBrowsableState.Never)>]
    let collisionPaddingValue (top: int option) (right: int option) (bottom: int option) (left: int option) =
        createObj [
            match top with
            | Some top -> "top", top
            | None -> ()
            match right with
            | Some right -> "right", right
            | None -> ()
            match bottom with
            | Some bottom -> "bottom", bottom
            | None -> ()
            match left with
            | Some left -> "left", left
            | None -> ()
        ]

    [<EditorBrowsable(EditorBrowsableState.Never)>]
    [<Erase>]
    let direction = {|
        ltr = prop.custom ("dir", "ltr")
        rtl = prop.custom ("dir", "rtl")
    |}

    [<EditorBrowsable(EditorBrowsableState.Never)>]
    [<Erase>]
    let orientation = {|
        horizontal = prop.custom ("orientation", "horizontal")
        vertical = prop.custom ("orientation", "vertical")
    |}

    [<EditorBrowsable(EditorBrowsableState.Never)>]
    [<Erase>]
    let side = {|
        top = prop.custom ("side", "top")
        right = prop.custom ("side", "right")
        bottom = prop.custom ("side", "bottom")
        left = prop.custom ("side", "left")
    |}

    [<EditorBrowsable(EditorBrowsableState.Never)>]
    [<Erase>]
    let align = {|
        center = prop.custom ("align", "center")
        start = prop.custom ("align", "start")
        end' = prop.custom ("align", "end")
    |}

    [<EditorBrowsable(EditorBrowsableState.Never)>]
    [<Erase>]
    let sticky = {|
        always = prop.custom ("sticky", "always")
        partial = prop.custom ("sticky", "partial")
    |}

    [<EditorBrowsable(EditorBrowsableState.Never)>]
    [<Erase>]
    let checked = {|
        boolean = prop.custom ("checkedState", "boolean")
        indeterminate = prop.custom ("checkedState", "indeterminate")
    |}


    [<EditorBrowsable(EditorBrowsableState.Never)>]
    [<Erase>]
    module accordion =
        let type' = {|
            single = prop.custom ("type", "single")
            multiple = prop.custom ("type", "multiple")
        |}

    type accordion =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline type' = accordion.type'
        static member inline value(value: string) = prop.custom ("value", value)
        static member inline defaultValue(value: string) = prop.custom ("defaultValue", value)
        static member inline onValueChange(value: string -> unit) = prop.custom ("onValueChange", value)
        static member inline value(value: string seq) = prop.custom ("value", value)
        static member inline defaultValue(value: string seq) = prop.custom ("defaultValue", value)
        static member inline onValueChange(value: string[] -> unit) = prop.custom ("onValueChange", value)
        static member inline collapsible = prop.custom ("collapsible", null)
        static member inline disabled = prop.custom ("disabled", null)
        static member inline dir = direction
        static member inline orientation = orientation

    type accordionItem =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline disabled = prop.custom ("disabled", null)
        static member inline value(value: string) = prop.custom ("value", value)

    type accordionTrigger =
        static member inline asChild = prop.custom ("asChild", null)

    type accordionContent =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline forceMount = prop.custom ("forceMount", null)

    type alertDialog =
        static member inline defaultOpen = prop.custom ("defaultOpen", null)
        static member inline open' = prop.custom ("open", null)
        static member inline onOpenChange(value: bool -> unit) = prop.custom ("onOpenChange", value)

    type alertDialogTrigger =
        static member inline asChild = prop.custom ("asChild", null)

    type alertDialogPortal =
        static member inline forceMount = prop.custom ("forceMount", null)
        static member inline container(value: HTMLElement) = prop.custom ("container", value)

    type alertDialogOverlay =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline forceMount = prop.custom ("forceMount", null)

    type alertDialogContent =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline forceMount = prop.custom ("forceMount", null)
        static member inline onOpenAutoFocus(value: Event -> unit) = prop.custom ("onOpenAutoFocus", value)
        static member inline onCloseAutoFocus(value: Event -> unit) = prop.custom ("onCloseAutoFocus", value)
        static member inline onEscapeKeyDown(value: KeyboardEvent -> unit) = prop.custom ("onEscapeKeyDown", value)

    type alertDialogCancel =
        static member inline asChild = prop.custom ("asChild", null)

    type alertDialogAction =
        static member inline asChild = prop.custom ("asChild", null)

    type alertDialogTitle =
        static member inline asChild = prop.custom ("asChild", null)

    type alertDialogDescription =
        static member inline asChild = prop.custom ("asChild", null)

    type aspectRatio =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline ratio(value: int) = prop.custom ("ratio", value)

    type avatar =
        static member inline asChild = prop.custom ("asChild", null)

    type avatarImage =
        static member inline asChild = prop.custom ("asChild", null)

        static member inline onLoadingStatusChange(value: string -> unit) =
            prop.custom ("onLoadingStatusChange", value)

    type avatarFallback =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline delayMs(value: int) = prop.custom ("delayMs", value)

    type checkbox =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline defaultChecked(value: bool option -> unit) = prop.custom ("defaultChecked", value)
        static member inline checked' = checked
        static member inline onCheckedChange(value: bool option -> unit) = prop.custom ("onCheckedChange", value)
        static member inline disabled = prop.custom ("disabled", null)
        static member inline required = prop.custom ("required", null)
        static member inline name(value: string) = prop.custom ("name", value)
        static member inline value(value: string) = prop.custom ("value", value)

    type collapsible =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline defaultOpen = prop.custom ("defaultOpen", null)
        static member inline open' = prop.custom ("open", null)
        static member inline onOpenChange(value: bool -> unit) = prop.custom ("onOpenChange", value)
        static member inline disabled = prop.custom ("disabled", null)

    type collapsibleTrigger =
        static member inline asChild = prop.custom ("asChild", null)

    type collapsibleContent =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline forceMount = prop.custom ("forceMount", null)

    type contextMenu =
        static member inline dir = direction
        static member inline onOpenChange(value: bool -> unit) = prop.custom ("onOpenChange", value)
        static member inline modal = prop.custom ("modal", null)

    type contextMenuTrigger =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline disabled = prop.custom ("disabled", null)

    type contextMenuPortal =
        static member inline forceMount = prop.custom ("forceMount", null)
        static member inline container(value: HTMLElement) = prop.custom ("container", value)

    type contextMenuContent =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline loop = prop.custom ("loop", null)
        static member inline onCloseAutoFocus(value: Event -> unit) = prop.custom ("onCloseAutoFocus", value)
        static member inline onEscapeKeyDown(value: KeyboardEvent -> unit) = prop.custom ("onEscapeKeyDown", value)

        static member inline onPointerDownOutside(value: PointerEvent -> unit) =
            prop.custom ("onPointerDownOutside", value)

        static member inline onFocusOutside(value: FocusEvent -> unit) = prop.custom ("onFocusOutside", value)

        static member inline onInteractOutside(value: Event -> unit) =
            prop.custom ("onInteractOutside", value)

        static member inline forceMount = prop.custom ("forceMount", null)
        static member inline alignOffset(value: int) = prop.custom ("alignOffset", value)
        static member inline avoidCollisions = prop.custom ("avoidCollisions", null)

        static member inline collisionBoundary(value: HTMLElement) =
            prop.custom ("collisionBoundary", value)

        static member inline collisionBoundary(value: HTMLElement array) =
            prop.custom ("collisionBoundary", value)

        static member inline collisionPadding(all: int) = prop.custom ("collisionPadding", all)

        static member inline collisionPadding(?top: int, ?right: int, ?bottom: int, ?left: int) =
            prop.custom ("collisionPadding", collisionPaddingValue top right bottom left)

        static member inline sticky = sticky
        static member inline hideWhenDetached = prop.custom ("hideWhenDetached", null)

    type contextMenuItem =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline disabled = prop.custom ("disabled", null)
        static member inline onSelect(value: Event -> unit) = prop.custom ("onSelect", value)
        static member inline textValue(value: string) = prop.custom ("textValue", value)

    type contextMenuGroup =
        static member inline asChild = prop.custom ("asChild", null)

    type contextMenuLabel =
        static member inline asChild = prop.custom ("asChild", null)

    type contextMenuCheckboxItem =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline checked' = checked
        static member inline onCheckedChange(value: bool -> unit) = prop.custom ("onCheckedChange", value)
        static member inline disabled = prop.custom ("disabled", null)
        static member inline onSelect(value: Event -> unit) = prop.custom ("onSelect", value)
        static member inline textValue(value: string) = prop.custom ("textValue", value)

    type contextMenuRadioGroup =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline value(value: string) = prop.custom ("value", value)
        static member inline onValueChange(value: string -> unit) = prop.custom ("onValueChange", value)

    type contextMenuRadioItem =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline value(value: string) = prop.custom ("value", value)
        static member inline disabled = prop.custom ("disabled", null)
        static member inline onSelect(value: Event -> unit) = prop.custom ("onSelect", value)
        static member inline textValue(value: string) = prop.custom ("textValue", value)

    type contextMenuSeparator =
        static member inline asChild = prop.custom ("asChild", null)

    type contextMenuSub =
        static member inline defaultOpen = prop.custom ("defaultOpen", null)
        static member inline open' = prop.custom ("open", null)
        static member inline onOpenChange(value: bool -> unit) = prop.custom ("onOpenChange", value)

    type contextMenuSubTrigger =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline disabled = prop.custom ("disabled", null)
        static member inline textValue(value: string) = prop.custom ("textValue", value)

    type contextMenuSubContent =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline loop = prop.custom ("loop", null)
        static member inline onEscapeKeyDown(value: KeyboardEvent -> unit) = prop.custom ("onEscapeKeyDown", value)

        static member inline onPointerDownOutside(value: PointerEvent -> unit) =
            prop.custom ("onPointerDownOutside", value)

        static member inline onFocusOutside(value: FocusEvent -> unit) = prop.custom ("onFocusOutside", value)

        static member inline onInteractOutside(value: Event -> unit) =
            prop.custom ("onInteractOutside", value)

        static member inline forceMount = prop.custom ("forceMount", null)
        static member inline sideOffset(value: int) = prop.custom ("sideOffset", value)
        static member inline alignOffset(value: int) = prop.custom ("alignOffset", value)
        static member inline avoidCollisions = prop.custom ("avoidCollisions", null)

        static member inline collisionBoundary(value: HTMLElement) =
            prop.custom ("collisionBoundary", value)

        static member inline collisionBoundary(value: HTMLElement array) =
            prop.custom ("collisionBoundary", value)

        static member inline collisionPadding(all: int) = prop.custom ("collisionPadding", all)

        static member inline collisionPadding(?top: int, ?right: int, ?bottom: int, ?left: int) =
            prop.custom ("collisionPadding", collisionPaddingValue top right bottom left)

        static member inline arrowPadding(value: int) = prop.custom ("arrowPadding", value)
        static member inline sticky = sticky
        static member inline hideWhenDetached = prop.custom ("hideWhenDetached", null)

    type dialog =
        static member inline defaultOpen = prop.custom ("defaultOpen", null)
        static member inline open' = prop.custom ("open", null)
        static member inline onOpenChange(value: bool -> unit) = prop.custom ("onOpenChange", value)
        static member inline modal = prop.custom ("modal", null)

    type dialogTrigger =
        static member inline asChild = prop.custom ("asChild", null)

    type dialogPortal =
        static member inline forceMount = prop.custom ("forceMount", null)
        static member inline container(value: HTMLElement) = prop.custom ("container", value)

    type dialogOverlay =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline forceMount = prop.custom ("forceMount", null)

    type dialogContent =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline forceMount = prop.custom ("forceMount", null)
        static member inline onOpenAutoFocus(value: Event -> unit) = prop.custom ("onOpenAutoFocus", value)
        static member inline onCloseAutoFocus(value: Event -> unit) = prop.custom ("onCloseAutoFocus", value)
        static member inline onEscapeKeyDown(value: KeyboardEvent -> unit) = prop.custom ("onEscapeKeyDown", value)

        static member inline onPointerDownOutside(value: PointerEvent -> unit) =
            prop.custom ("onPointerDownOutside", value)

        static member inline onInteractOutside(value: Event -> unit) =
            prop.custom ("onInteractOutside", value)

    type dialogClose =
        static member inline asChild = prop.custom ("asChild", null)

    type dialogTitle =
        static member inline asChild = prop.custom ("asChild", null)

    type dialogDescription =
        static member inline asChild = prop.custom ("asChild", null)

    type dropdownMenu =
        static member inline defaultOpen = prop.custom ("defaultOpen", null)
        static member inline open' = prop.custom ("open", null)
        static member inline onOpenChange(value: bool -> unit) = prop.custom ("onOpenChange", value)
        static member inline modal = prop.custom ("modal", null)
        static member inline dir = direction

    type dropdownMenuTrigger =
        static member inline asChild = prop.custom ("asChild", null)

    type dropdownMenuPortal =
        static member inline forceMount = prop.custom ("forceMount", null)
        static member inline container(value: HTMLElement) = prop.custom ("container", value)

    type dropdownMenuContent =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline loop = prop.custom ("loop", null)
        static member inline onCloseAutoFocus(value: Event -> unit) = prop.custom ("onCloseAutoFocus", value)
        static member inline onEscapeKeyDown(value: KeyboardEvent -> unit) = prop.custom ("onEscapeKeyDown", value)

        static member inline onPointerDownOutside(value: PointerEvent -> unit) =
            prop.custom ("onPointerDownOutside", value)

        static member inline onFocusOutside(value: FocusEvent -> unit) = prop.custom ("onFocusOutside", value)

        static member inline onInteractOutside(value: Event -> unit) =
            prop.custom ("onInteractOutside", value)

        static member inline forceMount = prop.custom ("forceMount", null)
        static member inline side = side
        static member inline sideOffset(value: int) = prop.custom ("sideOffset", value)
        static member inline align = align
        static member inline alignOffset(value: int) = prop.custom ("alignOffset", value)
        static member inline avoidCollisions = prop.custom ("avoidCollisions", null)

        static member inline collisionBoundary(value: HTMLElement) =
            prop.custom ("collisionBoundary", value)

        static member inline collisionBoundary(value: HTMLElement array) =
            prop.custom ("collisionBoundary", value)

        static member inline collisionPadding(all: int) = prop.custom ("collisionPadding", all)

        static member inline collisionPadding(?top: int, ?right: int, ?bottom: int, ?left: int) =
            prop.custom ("collisionPadding", collisionPaddingValue top right bottom left)

        static member inline arrowPadding(value: int) = prop.custom ("arrowPadding", value)
        static member inline sticky = sticky
        static member inline hideWhenDetached = prop.custom ("hideWhenDetached", null)

    type dropdownMenuItem =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline disabled = prop.custom ("disabled", null)
        static member inline onSelect(value: Event -> unit) = prop.custom ("onSelect", value)
        static member inline textValue(value: string) = prop.custom ("textValue", value)

    type dropdownMenuGroup =
        static member inline asChild = prop.custom ("asChild", null)

    type dropdownMenuLabel =
        static member inline asChild = prop.custom ("asChild", null)

    type dropdownMenuCheckboxItem =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline checked' = checked
        static member inline onCheckedChange(value: bool -> unit) = prop.custom ("onCheckedChange", value)
        static member inline disabled = prop.custom ("disabled", null)
        static member inline onSelect(value: Event -> unit) = prop.custom ("onSelect", value)
        static member inline textValue(value: string) = prop.custom ("textValue", value)

    type dropdownMenuRadioGroup =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline value(value: string) = prop.custom ("value", value)
        static member inline onValueChange(value: string -> unit) = prop.custom ("onValueChange", value)

    type dropdownMenuRadioItem =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline value(value: string) = prop.custom ("value", value)
        static member inline disabled = prop.custom ("disabled", null)
        static member inline onSelect(value: Event -> unit) = prop.custom ("onSelect", value)
        static member inline textValue(value: string) = prop.custom ("textValue", value)

    type dropdownMenuSeparator =
        static member inline asChild = prop.custom ("asChild", null)

    type dropdownMenuSub =
        static member inline defaultOpen = prop.custom ("defaultOpen", null)
        static member inline open' = prop.custom ("open", null)
        static member inline onOpenChange(value: bool -> unit) = prop.custom ("onOpenChange", value)

    type dropdownMenuSubTrigger =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline disabled = prop.custom ("disabled", null)
        static member inline textValue(value: string) = prop.custom ("textValue", value)

    type dropdownMenuSubContent =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline loop = prop.custom ("loop", null)
        static member inline onEscapeKeyDown(value: KeyboardEvent -> unit) = prop.custom ("onEscapeKeyDown", value)

        static member inline onPointerDownOutside(value: PointerEvent -> unit) =
            prop.custom ("onPointerDownOutside", value)

        static member inline onFocusOutside(value: FocusEvent -> unit) = prop.custom ("onFocusOutside", value)

        static member inline onInteractOutside(value: Event -> unit) =
            prop.custom ("onInteractOutside", value)

        static member inline forceMount = prop.custom ("forceMount", null)
        static member inline sideOffset(value: int) = prop.custom ("sideOffset", value)
        static member inline alignOffset(value: int) = prop.custom ("alignOffset", value)
        static member inline avoidCollisions = prop.custom ("avoidCollisions", null)

        static member inline collisionBoundary(value: HTMLElement) =
            prop.custom ("collisionBoundary", value)

        static member inline collisionBoundary(value: HTMLElement array) =
            prop.custom ("collisionBoundary", value)

        static member inline collisionPadding(all: int) = prop.custom ("collisionPadding", all)

        static member inline collisionPadding(?top: int, ?right: int, ?bottom: int, ?left: int) =
            prop.custom ("collisionPadding", collisionPaddingValue top right bottom left)

        static member inline arrowPadding(value: int) = prop.custom ("arrowPadding", value)
        static member inline sticky = sticky
        static member inline hideWhenDetached = prop.custom ("hideWhenDetached", null)

    type form =
        static member inline asChild = prop.custom ("asChild", null)

        static member inline onClearServerErrors(value: unit -> unit) =
            prop.custom ("onClearServerErrors", value)

    type hoverCard =
        static member inline defaultOpen = prop.custom ("defaultOpen", null)
        static member inline open' = prop.custom ("open", null)
        static member inline onOpenChange(value: bool -> unit) = prop.custom ("onOpenChange", value)
        static member inline open'Delay(value: int) = prop.custom ("openDelay", value)
        static member inline closeDelay(value: int) = prop.custom ("closeDelay", value)

    type hoverCardTrigger =
        static member inline asChild = prop.custom ("asChild", null)

    type hoverCardContent =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline forceMount = prop.custom ("forceMount", null)
        static member inline side = side
        static member inline sideOffset(value: int) = prop.custom ("sideOffset", value)
        static member inline align = align
        static member inline alignOffset(value: int) = prop.custom ("alignOffset", value)
        static member inline avoidCollisions = prop.custom ("avoidCollisions", null)

        static member inline collisionBoundary(value: HTMLElement) =
            prop.custom ("collisionBoundary", value)

        static member inline collisionBoundary(value: HTMLElement array) =
            prop.custom ("collisionBoundary", value)

        static member inline collisionPadding(all: int) = prop.custom ("collisionPadding", all)

        static member inline collisionPadding(?top: int, ?right: int, ?bottom: int, ?left: int) =
            prop.custom ("collisionPadding", collisionPaddingValue top right bottom left)

        static member inline arrowPadding(value: int) = prop.custom ("arrowPadding", value)
        static member inline sticky = sticky
        static member inline hideWhenDetached = prop.custom ("hideWhenDetached", null)

    type label =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline htmlFor(value: string) = prop.custom ("htmlFor", value)

    type menubar =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline defaultValue(value: string) = prop.custom ("defaultValue", value)
        static member inline value(value: string) = prop.custom ("value", value)
        static member inline onValueChange(value: int[] -> unit) = prop.custom ("onValueChange", value)
        static member inline dir = direction
        static member inline loop = prop.custom ("loop", null)

    type menubarMenu =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline value(value: string) = prop.custom ("value", value)

    type menubarTrigger =
        static member inline asChild = prop.custom ("asChild", null)

    type menubarPortal =
        static member inline forceMount = prop.custom ("forceMount", null)
        static member inline container(value: HTMLElement) = prop.custom ("container", value)

    type menubarContent =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline loop = prop.custom ("loop", null)
        static member inline onCloseAutoFocus(value: Event -> unit) = prop.custom ("onCloseAutoFocus", value)
        static member inline onEscapeKeyDown(value: KeyboardEvent -> unit) = prop.custom ("onEscapeKeyDown", value)

        static member inline onPointerDownOutside(value: PointerEvent -> unit) =
            prop.custom ("onPointerDownOutside", value)

        static member inline onFocusOutside(value: FocusEvent -> unit) = prop.custom ("onFocusOutside", value)

        static member inline onInteractOutside(value: Event -> unit) =
            prop.custom ("onInteractOutside", value)

        static member inline forceMount = prop.custom ("forceMount", null)
        static member inline side = side
        static member inline sideOffset(value: int) = prop.custom ("sideOffset", value)
        static member inline align = align
        static member inline alignOffset(value: int) = prop.custom ("alignOffset", value)
        static member inline avoidCollisions = prop.custom ("avoidCollisions", null)

        static member inline collisionBoundary(value: HTMLElement) =
            prop.custom ("collisionBoundary", value)

        static member inline collisionBoundary(value: HTMLElement array) =
            prop.custom ("collisionBoundary", value)

        static member inline collisionPadding(all: int) = prop.custom ("collisionPadding", all)

        static member inline collisionPadding(?top: int, ?right: int, ?bottom: int, ?left: int) =
            prop.custom ("collisionPadding", collisionPaddingValue top right bottom left)

        static member inline arrowPadding(value: int) = prop.custom ("arrowPadding", value)
        static member inline sticky = sticky
        static member inline hideWhenDetached = prop.custom ("hideWhenDetached", null)

    type menubarItem =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline disabled = prop.custom ("disabled", null)
        static member inline onSelect(value: Event -> unit) = prop.custom ("onSelect", value)
        static member inline textValue(value: string) = prop.custom ("textValue", value)

    type menubarGroup =
        static member inline asChild = prop.custom ("asChild", null)

    type menubarLabel =
        static member inline asChild = prop.custom ("asChild", null)

    type menubarCheckboxItem =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline checked' = checked
        static member inline onCheckedChange(value: bool -> unit) = prop.custom ("onCheckedChange", value)
        static member inline disabled = prop.custom ("disabled", null)
        static member inline onSelect(value: Event -> unit) = prop.custom ("onSelect", value)
        static member inline textValue(value: string) = prop.custom ("textValue", value)

    type menubarRadioGroup =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline value(value: string) = prop.custom ("value", value)
        static member inline onValueChange(value: string -> unit) = prop.custom ("onValueChange", value)

    type menubarRadioItem =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline value(value: string) = prop.custom ("value", value)
        static member inline disabled = prop.custom ("disabled", null)
        static member inline onSelect(value: Event -> unit) = prop.custom ("onSelect", value)
        static member inline textValue(value: string) = prop.custom ("textValue", value)

    type menubarSeparator =
        static member inline asChild = prop.custom ("asChild", null)

    type menubarSub =
        static member inline defaultOpen = prop.custom ("defaultOpen", null)
        static member inline open' = prop.custom ("open", null)
        static member inline onOpenChange(value: bool -> unit) = prop.custom ("onOpenChange", value)

    type menubarSubTrigger =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline disabled = prop.custom ("disabled", null)
        static member inline textValue(value: string) = prop.custom ("textValue", value)

    type menubarSubContent =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline loop = prop.custom ("loop", null)
        static member inline onEscapeKeyDown(value: KeyboardEvent -> unit) = prop.custom ("onEscapeKeyDown", value)

        static member inline onPointerDownOutside(value: PointerEvent -> unit) =
            prop.custom ("onPointerDownOutside", value)

        static member inline onFocusOutside(value: FocusEvent -> unit) = prop.custom ("onFocusOutside", value)

        static member inline onInteractOutside(value: Event -> unit) =
            prop.custom ("onInteractOutside", value)

        static member inline forceMount = prop.custom ("forceMount", null)
        static member inline sideOffset(value: int) = prop.custom ("sideOffset", value)
        static member inline alignOffset(value: int) = prop.custom ("alignOffset", value)
        static member inline avoidCollisions = prop.custom ("avoidCollisions", null)

        static member inline collisionBoundary(value: HTMLElement) =
            prop.custom ("collisionBoundary", value)

        static member inline collisionBoundary(value: HTMLElement array) =
            prop.custom ("collisionBoundary", value)

        static member inline collisionPadding(all: int) = prop.custom ("collisionPadding", all)

        static member inline collisionPadding(?top: int, ?right: int, ?bottom: int, ?left: int) =
            prop.custom ("collisionPadding", collisionPaddingValue top right bottom left)

        static member inline arrowPadding(value: int) = prop.custom ("arrowPadding", value)
        static member inline sticky = sticky
        static member inline hideWhenDetached = prop.custom ("hideWhenDetached", null)

    type navigationMenu =
        static member inline defaultValue(value: string) = prop.custom ("defaultValue", value)
        static member inline value(value: string) = prop.custom ("value", value)
        static member inline onValueChange(value: int[] -> unit) = prop.custom ("onValueChange", value)
        static member inline delayDuration(value: int) = prop.custom ("delayDuration", value)

        static member inline skipDelayDuration(value: int) =
            prop.custom ("skipDelayDuration", value)

        static member inline dir = direction
        static member inline orientation = orientation

    type navigationMenuList =
        static member inline asChild = prop.custom ("asChild", null)

    type navigationMenuItem =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline value(value: string) = prop.custom ("value", value)

    type navigationMenuTrigger =
        static member inline asChild = prop.custom ("asChild", null)

    type navigationMenuContent =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline onEscapeKeyDown(value: KeyboardEvent -> unit) = prop.custom ("onEscapeKeyDown", value)

        static member inline onPointerDownOutside(value: PointerEvent -> unit) =
            prop.custom ("onPointerDownOutside", value)

        static member inline onFocusOutside(value: FocusEvent -> unit) = prop.custom ("onFocusOutside", value)

        static member inline onInteractOutside(value: Event -> unit) =
            prop.custom ("onInteractOutside", value)

        static member inline forceMount = prop.custom ("forceMount", null)

    type navigationMenuLink =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline active = prop.custom ("active", null)
        static member inline onSelect(value: Event -> unit) = prop.custom ("onSelect", value)

    type navigationMenuIndicator =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline forceMount = prop.custom ("forceMount", null)

    type navigationMenuViewport =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline forceMount = prop.custom ("forceMount", null)

    type popover =
        static member inline defaultOpen = prop.custom ("defaultOpen", null)
        static member inline open' = prop.custom ("open", null)
        static member inline onOpenChange(value: bool -> unit) = prop.custom ("onOpenChange", value)
        static member inline modal = prop.custom ("modal", null)

    type popoverTrigger =
        static member inline asChild = prop.custom ("asChild", null)

    type popoverAnchor =
        static member inline asChild = prop.custom ("asChild", null)

    type popoverContent =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline onOpenAutoFocus(value: Event -> unit) = prop.custom ("onOpenAutoFocus", value)
        static member inline onCloseAutoFocus(value: Event -> unit) = prop.custom ("onCloseAutoFocus", value)
        static member inline onEscapeKeyDown(value: KeyboardEvent -> unit) = prop.custom ("onEscapeKeyDown", value)

        static member inline onPointerDownOutside(value: PointerEvent -> unit) =
            prop.custom ("onPointerDownOutside", value)

        static member inline onFocusOutside(value: FocusEvent -> unit) = prop.custom ("onFocusOutside", value)

        static member inline onInteractOutside(value: Event -> unit) =
            prop.custom ("onInteractOutside", value)

        static member inline forceMount = prop.custom ("forceMount", null)
        static member inline side = side
        static member inline sideOffset(value: int) = prop.custom ("sideOffset", value)
        static member inline align = align
        static member inline alignOffset(value: int) = prop.custom ("alignOffset", value)
        static member inline avoidCollisions = prop.custom ("avoidCollisions", null)

        static member inline collisionBoundary(value: HTMLElement) =
            prop.custom ("collisionBoundary", value)

        static member inline collisionBoundary(value: HTMLElement array) =
            prop.custom ("collisionBoundary", value)

        static member inline collisionPadding(all: int) = prop.custom ("collisionPadding", all)

        static member inline collisionPadding(?top: int, ?right: int, ?bottom: int, ?left: int) =
            prop.custom ("collisionPadding", collisionPaddingValue top right bottom left)

        static member inline arrowPadding(value: int) = prop.custom ("arrowPadding", value)
        static member inline sticky = sticky
        static member inline hideWhenDetached = prop.custom ("hideWhenDetached", null)

    type progress =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline value(value: int option) = prop.custom ("value", value)
        static member inline max(value: int) = prop.custom ("max", value)
        static member inline getValueLabel(value: int -> int -> string) = prop.custom ("getValueLabel", value)

    type radioGroup =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline defaultValue(value: string) = prop.custom ("defaultValue", value)
        static member inline value(value: string) = prop.custom ("value", value)
        static member inline onValueChange(value: int[] -> unit) = prop.custom ("onValueChange", value)
        static member inline disabled = prop.custom ("disabled", null)
        static member inline name(value: string) = prop.custom ("name", value)
        static member inline required = prop.custom ("required", null)
        static member inline orientation = orientation
        static member inline dir = direction
        static member inline loop = prop.custom ("loop", null)

    type radioGroupItem =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline value(value: string) = prop.custom ("value", value)
        static member inline disabled = prop.custom ("disabled", null)
        static member inline required = prop.custom ("required", null)


    [<EditorBrowsable(EditorBrowsableState.Never)>]
    [<Erase>]
    module scrollArea =
        let type' = {|
            auto = prop.custom ("type", "auto")
            always = prop.custom ("type", "always")
            scroll = prop.custom ("type", "scroll")
            hover = prop.custom ("type", "hover")
        |}

    type scrollArea =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline type' = scrollArea.type'
        static member inline scrollHideDelay(value: int) = prop.custom ("scrollHideDelay", value)
        static member inline dir = direction
        static member inline nonce(value: string) = prop.custom ("nonce", value)

    type select =
        static member inline defaultValue(value: string) = prop.custom ("defaultValue", value)
        static member inline value(value: string) = prop.custom ("value", value)
        static member inline onValueChange(value: string -> unit) = prop.custom ("onValueChange", value)
        static member inline defaultOpen = prop.custom ("defaultOpen", null)
        static member inline open' = prop.custom ("open", null)
        static member inline onOpenChange(value: bool -> unit) = prop.custom ("onOpenChange", value)
        static member inline dir = direction
        static member inline name(value: string) = prop.custom ("name", value)
        static member inline disabled = prop.custom ("disabled", null)
        static member inline required = prop.custom ("required", null)

    type selectTrigger =
        static member inline asChild = prop.custom ("asChild", null)

    type selectValue =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline placeholder(value: ReactElement) = prop.custom ("placeholder", value)


    [<EditorBrowsable(EditorBrowsableState.Never)>]
    [<Erase>]
    module selectContent =
        let position = {|
            itemAligned = prop.custom ("position", "item-aligned")
            popper = prop.custom ("position", "popper")
        |}

    type selectContent =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline onCloseAutoFocus(value: Event -> unit) = prop.custom ("onCloseAutoFocus", value)
        static member inline onEscapeKeyDown(value: KeyboardEvent -> unit) = prop.custom ("onEscapeKeyDown", value)

        static member inline onPointerDownOutside(value: PointerEvent -> unit) =
            prop.custom ("onPointerDownOutside", value)

        static member inline position = selectContent.position
        static member inline side = side
        static member inline sideOffset(value: int) = prop.custom ("sideOffset", value)
        static member inline align = align
        static member inline alignOffset(value: int) = prop.custom ("alignOffset", value)
        static member inline avoidCollisions = prop.custom ("avoidCollisions", null)

        static member inline collisionBoundary(value: HTMLElement) =
            prop.custom ("collisionBoundary", value)

        static member inline collisionBoundary(value: HTMLElement array) =
            prop.custom ("collisionBoundary", value)

        static member inline collisionPadding(all: int) = prop.custom ("collisionPadding", all)

        static member inline collisionPadding(?top: int, ?right: int, ?bottom: int, ?left: int) =
            prop.custom ("collisionPadding", collisionPaddingValue top right bottom left)

        static member inline arrowPadding(value: int) = prop.custom ("arrowPadding", value)
        static member inline sticky = sticky
        static member inline hideWhenDetached = prop.custom ("hideWhenDetached", null)

    type selectItem =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline value(value: string) = prop.custom ("value", value)
        static member inline disabled = prop.custom ("disabled", null)
        static member inline textValue(value: string) = prop.custom ("textValue", value)

    type selectScrollUpButton =
        static member inline asChild = prop.custom ("asChild", null)

    type selectScrollDownButton =
        static member inline asChild = prop.custom ("asChild", null)

    type selectGroup =
        static member inline asChild = prop.custom ("asChild", null)

    type selectLabel =
        static member inline asChild = prop.custom ("asChild", null)

    type selectSeparator =
        static member inline asChild = prop.custom ("asChild", null)

    type separator =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline orientation = orientation
        static member inline decorative = prop.custom ("decorative", null)

    type slider =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline defaultValue(value: int[]) = prop.custom ("defaultValue", value)
        static member inline value(value: int[]) = prop.custom ("value", value)
        static member inline onValueChange(value: int[] -> unit) = prop.custom ("onValueChange", value)
        static member inline onValueCommit(value: int[] -> unit) = prop.custom ("onValueCommit", value)
        static member inline name(value: string) = prop.custom ("name", value)
        static member inline disabled = prop.custom ("disabled", null)
        static member inline orientation = orientation
        static member inline dir = direction
        static member inline inverted = prop.custom ("inverted", null)
        static member inline min(value: int) = prop.custom ("min", value)
        static member inline max(value: int) = prop.custom ("max", value)
        static member inline step(value: int) = prop.custom ("step", value)

        static member inline minStepsBetweenThumbs(value: int) =
            prop.custom ("minStepsBetweenThumbs", value)

        static member inline form(value: string) = prop.custom ("form", value)

    type switch =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline defaultChecked = prop.custom ("defaultChecked", null)
        static member inline checked' = prop.custom ("checked", null)
        static member inline onCheckedChange(value: bool -> unit) = prop.custom ("onCheckedChange", value)
        static member inline disabled = prop.custom ("disabled", null)
        static member inline required = prop.custom ("required", null)
        static member inline name(value: string) = prop.custom ("name", value)
        static member inline value(value: string) = prop.custom ("value", value)


    [<EditorBrowsable(EditorBrowsableState.Never)>]
    [<Erase>]
    module tabs =
        let activationMode = {|
            automatic = prop.custom ("activationMode", "automatic")
            manual = prop.custom ("activationMode", "manual")
        |}

    type tabs =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline defaultValue(value: string) = prop.custom ("defaultValue", value)
        static member inline value(value: string) = prop.custom ("value", value)
        static member inline onValueChange(value: string -> unit) = prop.custom ("onValueChange", value)
        static member inline orientation = orientation
        static member inline dir = direction
        static member inline activationMode = tabs.activationMode

    type tabsList =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline loop = prop.custom ("loop", null)

    type tabsTrigger =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline value(value: string) = prop.custom ("value", value)
        static member inline disabled = prop.custom ("disabled", null)

    type tabsContent =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline value(value: string) = prop.custom ("value", value)
        static member inline forceMount = prop.custom ("forceMount", null)

    type toggle =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline defaultPressed = prop.custom ("defaultPressed", null)
        static member inline pressed = prop.custom ("pressed", null)
        static member inline onPressedChange(value: bool -> unit) = prop.custom ("onPressedChange", value)
        static member inline disabled = prop.custom ("disabled", null)


    [<EditorBrowsable(EditorBrowsableState.Never)>]
    [<Erase>]
    module toggleGroup =
        let type' = {|
            single = prop.custom ("activationMode", "single")
            multiple = prop.custom ("activationMode", "multiple")
        |}

    type toggleGroup =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline type' = toggleGroup.type'
        static member inline value(value: string) = prop.custom ("value", value)
        static member inline defaultValue(value: string) = prop.custom ("defaultValue", value)
        static member inline onValueChange(value: string -> unit) = prop.custom ("onValueChange", value)
        static member inline value(value: string seq) = prop.custom ("value", value)
        static member inline defaultValue(value: string seq) = prop.custom ("defaultValue", value)
        static member inline onValueChange(value: string[] -> unit) = prop.custom ("onValueChange", value)
        static member inline disabled = prop.custom ("disabled", null)
        static member inline rovingFocus = prop.custom ("rovingFocus", null)
        static member inline orientation = orientation
        static member inline dir = direction
        static member inline loop = prop.custom ("loop", null)

    type toggleGroupItem =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline value(value: string) = prop.custom ("value", value)
        static member inline disabled = prop.custom ("disabled", null)

    type tooltipProvider =
        static member inline delayDuration(value: int) = prop.custom ("delayDuration", value)

        static member inline skipDelayDuration(value: int) =
            prop.custom ("skipDelayDuration", value)

        static member inline disableHoverableContent = prop.custom ("disableHoverableContent", null)

    type tooltip =
        static member inline defaultOpen = prop.custom ("defaultOpen", null)
        static member inline open' = prop.custom ("open", null)
        static member inline onOpenChange(value: bool -> unit) = prop.custom ("onOpenChange", value)
        static member inline delayDuration(value: int) = prop.custom ("delayDuration", value)
        static member inline disableHoverableContent = prop.custom ("disableHoverableContent", null)

    type tooltipTrigger =
        static member inline asChild = prop.custom ("asChild", null)

    type tooltipContent =
        static member inline asChild = prop.custom ("asChild", null)
        static member inline arialabel(value: string) = prop.custom ("arialabel", value)
        static member inline onEscapeKeyDown(value: KeyboardEvent -> unit) = prop.custom ("onEscapeKeyDown", value)

        static member inline onPointerDownOutside(value: PointerEvent -> unit) =
            prop.custom ("onPointerDownOutside", value)

        static member inline forceMount = prop.custom ("forceMount", null)
        static member inline side = side
        static member inline sideOffset(value: int) = prop.custom ("sideOffset", value)
        static member inline align = align
        static member inline alignOffset(value: int) = prop.custom ("alignOffset", value)
        static member inline avoidCollisions = prop.custom ("avoidCollisions", null)

        static member inline collisionBoundary(value: HTMLElement) =
            prop.custom ("collisionBoundary", value)

        static member inline collisionBoundary(value: HTMLElement array) =
            prop.custom ("collisionBoundary", value)

        static member inline collisionPadding(all: int) = prop.custom ("collisionPadding", all)

        static member inline collisionPadding(?top: int, ?right: int, ?bottom: int, ?left: int) =
            prop.custom ("collisionPadding", collisionPaddingValue top right bottom left)

        static member inline arrowPadding(value: int) = prop.custom ("arrowPadding", value)
        static member inline sticky = sticky
        static member inline hideWhenDetached = prop.custom ("hideWhenDetached", null)
