// This file is auto-generated by the Generate.fsx script

namespace Feliz.Shadcn

[<AutoOpen>]
module Elements =
    open Fable.Core
    open Fable.Core.JsInterop
    open Feliz
    open Feliz.Shadcn.Helpers

    [<Erase>]
    type Shadcn =
        static member accordion (props: IReactProperty seq) = createElement(import "Accordion" "@/components/ui/accordion") props
        static member accordion (children: #seq<ReactElement>) = createElement(import "Accordion" "@/components/ui/accordion") [ prop.children (children :> ReactElement seq) ]
        static member alertDialog (props: IReactProperty seq) = createElement(import "AlertDialog" "@/components/ui/alert-dialog") props
        static member alertDialog (children: #seq<ReactElement>) = createElement(import "AlertDialog" "@/components/ui/alert-dialog") [ prop.children (children :> ReactElement seq) ]
        static member alert (props: IReactProperty seq) = createElement(import "Alert" "@/components/ui/alert") props
        static member alert (children: #seq<ReactElement>) = createElement(import "Alert" "@/components/ui/alert") [ prop.children (children :> ReactElement seq) ]
        static member aspectRatio (props: IReactProperty seq) = createElement(import "AspectRatio" "@/components/ui/aspect-ratio") props
        static member aspectRatio (children: #seq<ReactElement>) = createElement(import "AspectRatio" "@/components/ui/aspect-ratio") [ prop.children (children :> ReactElement seq) ]
        static member avatar (props: IReactProperty seq) = createElement(import "Avatar" "@/components/ui/avatar") props
        static member avatar (children: #seq<ReactElement>) = createElement(import "Avatar" "@/components/ui/avatar") [ prop.children (children :> ReactElement seq) ]
        static member badge (props: IReactProperty seq) = createElement(import "Badge" "@/components/ui/badge") props
        static member badge (children: #seq<ReactElement>) = createElement(import "Badge" "@/components/ui/badge") [ prop.children (children :> ReactElement seq) ]
        static member breadcrumb (props: IReactProperty seq) = createElement(import "Breadcrumb" "@/components/ui/breadcrumb") props
        static member breadcrumb (children: #seq<ReactElement>) = createElement(import "Breadcrumb" "@/components/ui/breadcrumb") [ prop.children (children :> ReactElement seq) ]
        static member button (props: IReactProperty seq) = createElement(import "Button" "@/components/ui/button") props
        static member button (children: #seq<ReactElement>) = createElement(import "Button" "@/components/ui/button") [ prop.children (children :> ReactElement seq) ]
        static member calendar (props: IReactProperty seq) = createElement(import "Calendar" "@/components/ui/calendar") props
        static member calendar (children: #seq<ReactElement>) = createElement(import "Calendar" "@/components/ui/calendar") [ prop.children (children :> ReactElement seq) ]
        static member card (props: IReactProperty seq) = createElement(import "Card" "@/components/ui/card") props
        static member card (children: #seq<ReactElement>) = createElement(import "Card" "@/components/ui/card") [ prop.children (children :> ReactElement seq) ]
        static member carousel (props: IReactProperty seq) = createElement(import "Carousel" "@/components/ui/carousel") props
        static member carousel (children: #seq<ReactElement>) = createElement(import "Carousel" "@/components/ui/carousel") [ prop.children (children :> ReactElement seq) ]
        static member chartContainer (props: IReactProperty seq) = createElement(import "ChartContainer" "@/components/ui/chart") props
        static member chartContainer (children: #seq<ReactElement>) = createElement(import "ChartContainer" "@/components/ui/chart") [ prop.children (children :> ReactElement seq) ]
        static member checkbox (props: IReactProperty seq) = createElement(import "Checkbox" "@/components/ui/checkbox") props
        static member checkbox (children: #seq<ReactElement>) = createElement(import "Checkbox" "@/components/ui/checkbox") [ prop.children (children :> ReactElement seq) ]
        static member collapsible (props: IReactProperty seq) = createElement(import "Collapsible" "@/components/ui/collapsible") props
        static member collapsible (children: #seq<ReactElement>) = createElement(import "Collapsible" "@/components/ui/collapsible") [ prop.children (children :> ReactElement seq) ]
        static member command (props: IReactProperty seq) = createElement(import "Command" "@/components/ui/command") props
        static member command (children: #seq<ReactElement>) = createElement(import "Command" "@/components/ui/command") [ prop.children (children :> ReactElement seq) ]
        static member contextMenu (props: IReactProperty seq) = createElement(import "ContextMenu" "@/components/ui/context-menu") props
        static member contextMenu (children: #seq<ReactElement>) = createElement(import "ContextMenu" "@/components/ui/context-menu") [ prop.children (children :> ReactElement seq) ]
        static member dialog (props: IReactProperty seq) = createElement(import "Dialog" "@/components/ui/dialog") props
        static member dialog (children: #seq<ReactElement>) = createElement(import "Dialog" "@/components/ui/dialog") [ prop.children (children :> ReactElement seq) ]
        static member drawer (props: IReactProperty seq) = createElement(import "Drawer" "@/components/ui/drawer") props
        static member drawer (children: #seq<ReactElement>) = createElement(import "Drawer" "@/components/ui/drawer") [ prop.children (children :> ReactElement seq) ]
        static member dropdownMenu (props: IReactProperty seq) = createElement(import "DropdownMenu" "@/components/ui/dropdown-menu") props
        static member dropdownMenu (children: #seq<ReactElement>) = createElement(import "DropdownMenu" "@/components/ui/dropdown-menu") [ prop.children (children :> ReactElement seq) ]
        static member form (props: IReactProperty seq) = createElement(import "Form" "@/components/ui/form") props
        static member form (children: #seq<ReactElement>) = createElement(import "Form" "@/components/ui/form") [ prop.children (children :> ReactElement seq) ]
        static member hoverCard (props: IReactProperty seq) = createElement(import "HoverCard" "@/components/ui/hover-card") props
        static member hoverCard (children: #seq<ReactElement>) = createElement(import "HoverCard" "@/components/ui/hover-card") [ prop.children (children :> ReactElement seq) ]
        static member inputOTP (props: IReactProperty seq) = createElement(import "InputOTP" "@/components/ui/input-otp") props
        static member inputOTP (children: #seq<ReactElement>) = createElement(import "InputOTP" "@/components/ui/input-otp") [ prop.children (children :> ReactElement seq) ]
        static member input (props: IReactProperty seq) = createElement(import "Input" "@/components/ui/input") props
        static member input (children: #seq<ReactElement>) = createElement(import "Input" "@/components/ui/input") [ prop.children (children :> ReactElement seq) ]
        static member label (props: IReactProperty seq) = createElement(import "Label" "@/components/ui/label") props
        static member label (children: #seq<ReactElement>) = createElement(import "Label" "@/components/ui/label") [ prop.children (children :> ReactElement seq) ]
        static member menubar (props: IReactProperty seq) = createElement(import "Menubar" "@/components/ui/menubar") props
        static member menubar (children: #seq<ReactElement>) = createElement(import "Menubar" "@/components/ui/menubar") [ prop.children (children :> ReactElement seq) ]
        static member navigationMenu (props: IReactProperty seq) = createElement(import "NavigationMenu" "@/components/ui/navigation-menu") props
        static member navigationMenu (children: #seq<ReactElement>) = createElement(import "NavigationMenu" "@/components/ui/navigation-menu") [ prop.children (children :> ReactElement seq) ]
        static member pagination (props: IReactProperty seq) = createElement(import "Pagination" "@/components/ui/pagination") props
        static member pagination (children: #seq<ReactElement>) = createElement(import "Pagination" "@/components/ui/pagination") [ prop.children (children :> ReactElement seq) ]
        static member popover (props: IReactProperty seq) = createElement(import "Popover" "@/components/ui/popover") props
        static member popover (children: #seq<ReactElement>) = createElement(import "Popover" "@/components/ui/popover") [ prop.children (children :> ReactElement seq) ]
        static member progress (props: IReactProperty seq) = createElement(import "Progress" "@/components/ui/progress") props
        static member progress (children: #seq<ReactElement>) = createElement(import "Progress" "@/components/ui/progress") [ prop.children (children :> ReactElement seq) ]
        static member radioGroup (props: IReactProperty seq) = createElement(import "RadioGroup" "@/components/ui/radio-group") props
        static member radioGroup (children: #seq<ReactElement>) = createElement(import "RadioGroup" "@/components/ui/radio-group") [ prop.children (children :> ReactElement seq) ]
        static member resizablePanelGroup (props: IReactProperty seq) = createElement(import "ResizablePanelGroup" "@/components/ui/resizable") props
        static member resizablePanelGroup (children: #seq<ReactElement>) = createElement(import "ResizablePanelGroup" "@/components/ui/resizable") [ prop.children (children :> ReactElement seq) ]
        static member scrollArea (props: IReactProperty seq) = createElement(import "ScrollArea" "@/components/ui/scroll-area") props
        static member scrollArea (children: #seq<ReactElement>) = createElement(import "ScrollArea" "@/components/ui/scroll-area") [ prop.children (children :> ReactElement seq) ]
        static member select (props: IReactProperty seq) = createElement(import "Select" "@/components/ui/select") props
        static member select (children: #seq<ReactElement>) = createElement(import "Select" "@/components/ui/select") [ prop.children (children :> ReactElement seq) ]
        static member separator (props: IReactProperty seq) = createElement(import "Separator" "@/components/ui/separator") props
        static member separator (children: #seq<ReactElement>) = createElement(import "Separator" "@/components/ui/separator") [ prop.children (children :> ReactElement seq) ]
        static member sheet (props: IReactProperty seq) = createElement(import "Sheet" "@/components/ui/sheet") props
        static member sheet (children: #seq<ReactElement>) = createElement(import "Sheet" "@/components/ui/sheet") [ prop.children (children :> ReactElement seq) ]
        static member sidebar (props: IReactProperty seq) = createElement(import "Sidebar" "@/components/ui/sidebar") props
        static member sidebar (children: #seq<ReactElement>) = createElement(import "Sidebar" "@/components/ui/sidebar") [ prop.children (children :> ReactElement seq) ]
        static member skeleton (props: IReactProperty seq) = createElement(import "Skeleton" "@/components/ui/skeleton") props
        static member skeleton (children: #seq<ReactElement>) = createElement(import "Skeleton" "@/components/ui/skeleton") [ prop.children (children :> ReactElement seq) ]
        static member slider (props: IReactProperty seq) = createElement(import "Slider" "@/components/ui/slider") props
        static member slider (children: #seq<ReactElement>) = createElement(import "Slider" "@/components/ui/slider") [ prop.children (children :> ReactElement seq) ]
        static member toaster (props: IReactProperty seq) = createElement(import "Toaster" "@/components/ui/sonner") props
        static member toaster (children: #seq<ReactElement>) = createElement(import "Toaster" "@/components/ui/sonner") [ prop.children (children :> ReactElement seq) ]
        static member switch (props: IReactProperty seq) = createElement(import "Switch" "@/components/ui/switch") props
        static member switch (children: #seq<ReactElement>) = createElement(import "Switch" "@/components/ui/switch") [ prop.children (children :> ReactElement seq) ]
        static member table (props: IReactProperty seq) = createElement(import "Table" "@/components/ui/table") props
        static member table (children: #seq<ReactElement>) = createElement(import "Table" "@/components/ui/table") [ prop.children (children :> ReactElement seq) ]
        static member tabs (props: IReactProperty seq) = createElement(import "Tabs" "@/components/ui/tabs") props
        static member tabs (children: #seq<ReactElement>) = createElement(import "Tabs" "@/components/ui/tabs") [ prop.children (children :> ReactElement seq) ]
        static member textarea (props: IReactProperty seq) = createElement(import "Textarea" "@/components/ui/textarea") props
        static member textarea (children: #seq<ReactElement>) = createElement(import "Textarea" "@/components/ui/textarea") [ prop.children (children :> ReactElement seq) ]
        static member toggleGroup (props: IReactProperty seq) = createElement(import "ToggleGroup" "@/components/ui/toggle-group") props
        static member toggleGroup (children: #seq<ReactElement>) = createElement(import "ToggleGroup" "@/components/ui/toggle-group") [ prop.children (children :> ReactElement seq) ]
        static member toggle (props: IReactProperty seq) = createElement(import "Toggle" "@/components/ui/toggle") props
        static member toggle (children: #seq<ReactElement>) = createElement(import "Toggle" "@/components/ui/toggle") [ prop.children (children :> ReactElement seq) ]
        static member tooltip (props: IReactProperty seq) = createElement(import "Tooltip" "@/components/ui/tooltip") props
        static member tooltip (children: #seq<ReactElement>) = createElement(import "Tooltip" "@/components/ui/tooltip") [ prop.children (children :> ReactElement seq) ]
